### ISSUE TITLE
add one env to turn off running install_demo_configuration.sh in production

### ISSUE THREAD

**Issue by yuecong** [opendistro-for-elasticsearch/opendistro-build#10]
Can I propose to add one system environment variable to allow users to turn off run this script in their production? By doing this, users can easily just use the same docker image in their production environment. 

https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/elasticsearch/docker/build/elasticsearch/bin/docker-entrypoint.sh#L88

If you guys agree, I can have one PR and ask for a review.

**Comment by val16384** [comment]
Good suggestion.

Now is only possibly to rewrite image Docker file or to  repllace  install_demo_configuration.sh with  empty file, in compose file.
volumes:
./elasticsearch/config/disabledemo.sh:/usr/share/elasticsearch/plugins/opendistro_security/tools/install_demo_configuration.sh

**Comment by yuecong** [comment]
thanks for the workaround. would you agree that we support have users able to disable it using some system env, e.g. is set DISABLE_INSTALL_DEMO_CONFIG to true, just do not run the script.

**Comment by alolita** [comment]
Hi @yuecong Feel free to raise a PR - thanks for suggesting this change.
