### ISSUE TITLE
Improve knn library install from preInstall script

### ISSUE THREAD

**Issue by stannie42** [opendistro-for-elasticsearch/opendistro-build#108]
Hello,

I need to install opendistroforelasticsearch package in a disconnected environment. The package is retrieved via an apt proxy, however the package directly does some wget in the preInstall script. Could opendistro-build embed the knn library directly in its package and avoid this wget ?

Thanks.

**Comment by weicongs-amazon** [comment]
Hi @stannie42  This issue is the same with #120. our team is working on fixing it.
