### ISSUE TITLE
Not so elegant way to distribute shared objects inside RPM  - kNN plugin installer

### ISSUE THREAD

**Issue by cr0ssmind** [opendistro-for-elasticsearch/opendistro-build#118]
Hello Guys,

after v 1.6.0 installation started hanging I have checked the RPM and it shocked me little bit.
This is not so elegant and "enterprise friendly" way to distribute - especially -  shared objects.
Why don't you distribute it as standalone package as other components?

```
 RPM_OS=linux 
 RPM_PACKAGE_NAME=opendistroforelasticsearch 
 RPM_PACKAGE_VERSION=1.6.0 
 RPM_PACKAGE_RELEASE=1 

echo "Fetching kNN library"
FILE=/usr/lib/libKNNIndexV1_7_3_6.so
if [ -f "$FILE" ]
then
    echo "$FILE exist: removing $FILE"
    sudo rm $FILE
fi
FILE=/libKNNIndexV1_7_3_6.zip
if [ -f "$FILE" ]
then
    echo "$FILE exist: removing $FILE"
    sudo rm $FILE
fi
wget https://d3g5vo6xdbdb9a.cloudfront.net/downloads/k-NN-lib/libKNNIndexV1_7_3_6.zip \
&& unzip libKNNIndexV1_7_3_6.zip \
&& mv libKNNIndexV1_7_3_6.so /usr/lib \
&& rm libKNNIndexV1_7_3_6.zip
```

**Comment by rishabh6788** [comment]
Hey @cr0ssmind ,

Thanks for flagging the issue. 
Could you please elaborate more on hanging issue?
Was it due to k-NN plugin download part?
Were you able to finally run the odfe-1.6.0?

**Comment by cr0ssmind** [comment]
Dear @rishabh6788 ,

there was everything fine with the download url. 
The issue here is security related that the odfe-16.0 installer uses an external wget (from a closed enterprise network point of view) download inside a signed rpm: 
`wget https://d3g5vo6xdbdb9a.cloudfront.net/downloads/k-NN-lib/libKNNIndexV1_7_3_6.zip`
and there is no warranty for integrity ( eg. hash calculation ) so it can be a potential attack vector.

My question is here: why don't you distribute this **libKNNIndexV1_7_3_6.so** inside the RPM?

If somebody synchronyze the odfe rpm repository inwards an enterprise repository ( that is secured with firewall ) they can't install it because the installer wants to download the .zip file from that external source.

**Comment by oranenj** [comment]
This issue prevents us from upgrading Opendistro, as our Elasticsearch hosts don't have internet access. I am not sure why, but in our case the lack of internet access also caused yum to hang, leading to a corrupted yum transaction as it had to be terminated mid-installation

Even if you ignore the part where a noarch package installs architecture-dependent files, downloading stuff from the internet is *not* something you should do in RPM scripts for *any* reason. You don't even verify the download in any way.

**Comment by rishabh6788** [comment]
Hi all,

Thanks for your patience, we are working on to address this issue and will try to provide you a workaround.

**Comment by alolita** [comment]
Hi @cr0ssmind @oranenj - Thanks for flagging the issue. We're aware of this and are looking at the best way to solve this. We welcome any improvements you may have.

**Comment by alolita** [comment]
@weicongs-amazon @vamshin can you provide more details

**Comment by weicongs-amazon** [comment]
Hi @oranenj @cr0ssmind our team is working on fix the issue. In the meanwhile, one workaround you probably can try with:
```shell
 #Get all needed rpms
 sudo curl https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo -o /etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo
 sudo yum install --downloadonly --downloaddir=opendistro-rpms opendistroforelasticsearch-1.7.0
 cd opendistro-rpms
 #Remove the opendistroforelasticsearch rpm
 sudo rm -rf opendistroforelasticsearch-1.7.0.rpm 

 #Get the libKNNIndexV1_7_3_6.so lib file
 wget https://d3g5vo6xdbdb9a.cloudfront.net/downloads/k-NN-lib/libKNNIndexV1_7_3_6.zip
 unzip libKNNIndexV1_7_3_6.zip

 #copy the rpms and lib file to servers of your cluster
 #install odfe
 sudo yum localinstall -y *.rpm
 #mv the libKNNIndexV1_7_3_6.so lib file to /usr/lib
 sudo mv libKNNIndexV1_7_3_6.so /usr/lib/
 sudo systemctl start elasticsearch.service
```

The key idea is that remove opendistroforelasticsearch-x.x.x.rpm and install the other RPMs and libKNNIndexV1_7_3_6 manually.

**Comment by weicongs-amazon** [comment]
same issue with #120. close this one. pls leave your comments in #120 if you still have issues, thankis
