### ISSUE TITLE
ODFE Kibana 1.6 tarball doesn't work on MAC

### ISSUE THREAD

**Issue by penghuo** [opendistro-for-elasticsearch/opendistro-build#127]
Follow the doc https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/#run-kibana-using-the-tarball.
When running the kibana, it show the error messages.
```
./bin/kibana: line 24: /Users/penghuo/release/opendistro/opendistroforelasticsearch-kibana/bin/../node/bin/node: cannot execute binary file
./bin/kibana: line 24: /Users/penghuo/release/opendistro/opendistroforelasticsearch-kibana/bin/../node/bin/node: Undefined error: 0
```
I think either we call out it only running on Linux or provide the Mac version.

**Comment by alolita** [comment]
Hi @penghuo we don't support MacOS yet but it is on our backlog.

**Comment by weicongs-amazon** [comment]
close this one. use  https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/214 to track this feature
