### ISSUE TITLE
How to make odfe to running on arm64 server ?

### ISSUE THREAD

**Issue by leanderli** [opendistro-for-elasticsearch/opendistro-build#130]

**Comment by alolita** [comment]
Hi @leanderli currently Open Distro doesn't support ARM64 - can you share your use case for this request so that we can consider for our backlog? Thanks!

**Comment by leanderli** [comment]
I need to use odfe with aarch64 in my server station and also odfe-kibana.

After I read [opendistro-build/elasticsearch/linux_distributions/opendistro-tar-build.sh] that it looks like just use elastic elasticsearch and Open Distro plugins make build together to get Open Distro for Elasticsearch. 

Is that means is useful if I can build elastic elasticsearch for arm64 server success and then make build with Open Distro plugins together?

Is there has some incompatible codes in Open Distro plugins doesn't support arm64 server?

Thanks!

**Comment by weicongs-amazon** [comment]
Hi @leanderli  I think you can try the way mentioned above. but one more thing is related to KNN library. You probably need recompile the it with the similar way like this: https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/elasticsearch/linux_distributions/k-NN-lib-buildscripts/build-kNNlib-rpm.sh 

if you don't need knn plugin, you can just simply remove it. then have a try to see if it works. Feel free to share any issue to this thread if you have. Thanks

**Comment by boostchicken** [comment]
@alolita My use case is wanting to save cost with the new m6g instances.

**Comment by leanderli** [comment]
Ok,thanks! I will try to do it and share the lastest issue for you.

**Comment by weicongs-amazon** [comment]
Close this issue. Feel free to reopen it to share new issue.
