### ISSUE TITLE
How to set password for `admin` user during bootstrapping the cluster?

### ISSUE THREAD

**Issue by kamolhasan** [opendistro-for-elasticsearch/opendistro-build#148]
I'm using the helm chart to deploy Elasticsearch on a Kubernetes cluster. Is it possible to provide the password for `admin` user while bootstrapping the cluster? I know that it can be changed by entering into a master node and generating new hash for new passwords and so on.

Is there any environ variable like `ELASTICSEARCH_PASSWORD` which is already there for kibana deployment?

Or is it possible to pass them via config files like `elasticsearch.yml`?

**Comment by weicongs-amazon** [comment]
Hi @kamolhasan could you try to use the way mentioned in the doc: https://aws.amazon.com/blogs/opensource/change-passwords-open-distro-for-elasticsearch/ to reset your password?

**Comment by an-sush** [comment]
@kamolhasan not really along with bootstrap but what you can do is to create a secret object upfront and then [pass the secret name](https://github.com/opendistro-for-elasticsearch/community/blob/c1f2802205eb11c0fdbbbef909b0e33e90ea2ad5/open-distro-elasticsearch-kubernetes/helm/opendistro-es/values.yaml#L131) in [values.yaml](https://github.com/opendistro-for-elasticsearch/community/blob/master/open-distro-elasticsearch-kubernetes/helm/opendistro-es/values.yaml).

[Example](https://github.com/opendistro-for-elasticsearch/community/blob/master/open-distro-elasticsearch-kubernetes/helm/opendistro-es/templates/elasticsearch/es-config-secret.yaml) to create a secret object (remember to remove the helm template code and make it a raw k8s yml)

**Comment by weicongs-amazon** [comment]
close the issue. feel free to reopen it if you still have issue

**Comment by chetnuy** [comment]
Please explain in more detail.
