### ISSUE TITLE
Incorrect image of elastic 1.2.0 on the hub.docker.com

### ISSUE THREAD

**Issue by e11it** [opendistro-for-elasticsearch/opendistro-build#15]
Hello!

@mohit0193,
Same image of elasticsearch as 1.1.0 was tagged as 1.2.0 on hub.docker.com (https://hub.docker.com/r/amazon/opendistro-for-elasticsearch/tags).
```
1.2.0 604.77 MB
69ab257b3ccf
```
AND
```
1.1.0 604.77 MB
69ab257b3ccf
```

**Comment by mohit0193** [comment]
Thanks @e11it , I have changed image tag.
