### ISSUE TITLE
Unable to connect to ODFE Docker Container using the Spring Boot App

### ISSUE THREAD

**Issue by sureshkoduri123** [opendistro-for-elasticsearch/opendistro-build#153]
Am unable to connect ODFE Docker Container from a Java Spring Boot App. The following error is seen:
`org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{_nQbb0bvTTi0NOGs_Jm8Dw}{localhost}{127.0.0.1:9200}]`

Application properties:
```
spring.data.elasticsearch.cluster-name=odfe-cluster
spring.data.elasticsearch.cluster-nodes=localhost:9200
```

**Comment by weicongs-amazon** [comment]
Hi @sureshkoduri123  have you tried to access the endpoint with curl command? https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/ could you share the output of it?

**Comment by weicongs-amazon** [comment]
close this issue firstly. if you still have issue, feel free to reopen it

**Comment by sureshkoduri123** [comment]
@weicongs-amazon when I run the following curl command, I get this output:
`curl -XGET https://localhost:9200 -u admin:admin --insecure`
`{
  "name" : "dc070ebe91e9",
  "cluster_name" : "my-cluster",
  "cluster_uuid" : "neFiF5W1Q1Sq-bCpELKirA",
  "version" : {
    "number" : "7.6.1",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "aa751e09be0a5072e8570670309b1f12348f023b",
    "build_date" : "2020-02-29T00:15:25.529771Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
`
After updating the `application.properties` file of spring boot app with:
`
ES_URL=https://admin:admin@localhost:9200
`
I am getting this error:
`
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
NOTE: Am using `RestHighLevelClient` for connecting the cluster

**Comment by weicongs-amazon** [comment]
this is related to certification. in the curl command, --insecure is used to skip the certification. If you wanna use this env in your cluster, you can also skip the certification in http client. btw, it's not recommended for production env. it's better to take a look how to set up the security related configuration for production env. https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker-security/
