### ISSUE TITLE
HELM - Upgrade not possible

### ISSUE THREAD

**Issue by Crazyigor1987** [opendistro-for-elasticsearch/opendistro-build#154]
I'm running Open Distro v1.6.0 on Kubernetes installed with HELM. After I wanted to upgrade, i get those errors.

My command
`helm upgrade --install elasticsearch --namespace elasticsearch --values=./values.yaml ./opendistro-es-1.7.0.tgz
`

E0515 14:15:05.773952   10696 portforward.go:372] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:33755->127.0.0.1:41362: write tcp4 127.0.0.1:33755->127.0.0.1:41362: write: broken pipe

UPGRADE FAILED

Error: Deployment.apps "elasticsearch-opendistro-es-client" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"elasticsearch-opendistro-es", "heritage":"Tiller", "release":"elasticsearch", "role":"client"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && Deployment.apps "elasticsearch-opendistro-es-kibana" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"elasticsearch-opendistro-es", "heritage":"Tiller", "release":"elasticsearch", "role":"kibana"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && StatefulSet.apps "elasticsearch-opendistro-es-data" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && StatefulSet.apps "elasticsearch-opendistro-es-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

Error: UPGRADE FAILED: Deployment.apps "elasticsearch-opendistro-es-client" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"elasticsearch-opendistro-es", "heritage":"Tiller", "release":"elasticsearch", "role":"client"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && Deployment.apps "elasticsearch-opendistro-es-kibana" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"elasticsearch-opendistro-es", "heritage":"Tiller", "release":"elasticsearch", "role":"kibana"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && StatefulSet.apps "elasticsearch-opendistro-es-data" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && StatefulSet.apps "elasticsearch-opendistro-es-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

**Comment by alolita** [comment]
Hi @Crazyigor1987 sorry to see you're running into this issue. We'll take a look and respond back.

**Comment by an-sush** [comment]
@Crazyigor1987  I updated the [imageTag](https://github.com/opendistro-for-elasticsearch/community/blob/c1f2802205eb11c0fdbbbef909b0e33e90ea2ad5/open-distro-elasticsearch-kubernetes/helm/opendistro-es/values.yaml#L17) in values.yml (its present in 2 places in this file) and then run helm upgrade:

```bash
# cd to https://github.com/opendistro-for-elasticsearch/community/tree/master/open-distro-elasticsearch-kubernetes/helm
helm upgrade --install  --wait opendistro-es
```
It worked fine and opendistro was upgraded

**Comment by weicongs-amazon** [comment]
close this issue. feel free to reopen it if you still have issue
