### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by eluchsinger** [opendistro-for-elasticsearch/opendistro-build#16]
Is it possible to provide a download for Windows? I can't run Docker on my environment, but we use Windows.

(Migrated from https://github.com/opendistro/for-elasticsearch/issues/45)

**Comment by alolita** [comment]
@eluchsinger we're working on providing a Windows image. Stay tuned.

Please share more details about your Windows setup for us to factor the configuration in our tests.

**Comment by eluchsinger** [comment]
Sorry, I meant we can use docker, but we only have Windows containers. I'll probably build my own Docker image with your Windows build so I can run it inside Windows containers.

**Comment by alolita** [comment]
Windows support for Open Distro was added in 1.3 - see https://opendistro.github.io/for-elasticsearch-docs/docs/install/windows/ 

Closing issue.
