### ISSUE TITLE
RPM for v1.6.0 is has broken

### ISSUE THREAD

**Issue by tdinucci** [opendistro-for-elasticsearch/opendistro-build#162]
It seems since the release of v1.7.0 the RPM for v1.6.0 is broken. When installing it is attempting to pull the anomaly detection plugin which wasn’t part of the old version:

```
--> Processing Dependency: opendistro-anomaly-detection >= 1.6.0 for package: opendistroforelasticsearch-1.6.0-1.noarch
```

Please advise how I can use the old RPM.

Thanks

**Comment by weicongs-amazon** [comment]
@tdinucci  There is a bug in the 1.7.0 release. we have fixed it. could you try it again?

**Comment by tdinucci** [comment]
Thank you - things look better now 👍
