### ISSUE TITLE
Packages for Windows

### ISSUE THREAD

**Issue by askids** [opendistro-for-elasticsearch/opendistro-build#18]
It would be useful to provide open distro packages for Windows Servers 2012/2016 as there are many current users of Elasticsearch running on windows and may want to switch from native to Open Distro because of the added features.

Thanks!

**Comment by alolita** [comment]
Hi @askids @cmg-dev thanks for your patience. We got a community contribution for the installer script and are currently evaluating it. If you're interested, it would be great to have your review and help in building and testing the alpha version. Let me know :-)

**Comment by askids** [comment]
@alolita I can help in the review.

**Comment by Paulomart** [comment]
Hi, @askids were can I find the contribution/PRs for windows. I would like to help test them.

**Comment by alolita** [comment]
@askids @Paulomart - thanks for being interested in testing. Will ping you the link for downloading the package to test.

**Comment by askids** [comment]
@alolita any updates on by when we can expect to get a version to test?

**Comment by aetter** [comment]
https://opendistro.github.io/for-elasticsearch-docs/docs/install/windows/
