### ISSUE TITLE
Script to collect the corresponding source is missing from the build

### ISSUE THREAD

**Issue by pombredanne** [opendistro-for-elasticsearch/opendistro-build#2]
It would make sense to be able to build a source archive instead of only dealing with binaries.
It does not instill confidence to have an open source project without source code handy.

**Comment by gabrielcalderon** [comment]
I think it's because they are using the prebuilt binaryies from Elastic. It just makes things easier, why rebuild the source?

**Comment by armijnhemel** [comment]
> I think it's because they are using the prebuilt binaryies from Elastic. It just makes things easier, why rebuild the source?

There are people who think this is important, for example the "reproducible builds" project.

**Comment by alolita** [comment]
As folks on the thread stated, Open Distro uses upstream binaries and the build scripts reflect that. You can build Open Distro plugins from source. For e.g. you can build the security plugin from source following these steps https://github.com/opendistro-for-elasticsearch/security-parent/blob/master/README.md Please feel free to enhance the current scripts. :-)
