### ISSUE TITLE
Need better explanation of what I'm doing with use of helm chart

### ISSUE THREAD

**Issue by matty1979** [opendistro-for-elasticsearch/opendistro-build#200]
I'm trying to deploy the helm chart and I'm confused as to what to do to make a config.yml apply during the bootstrap of the helm chart. 

I thought following the example of the config.yml, adding it on the values.yml of configSecret: "security-config" 
kubectl create secret generic security-config --from-file=config.yml

Deployed via helm following the directions, but nothing has changed on my deployment. It's not added in the the openid_connect options on kibana. 

What am I doing incorrectly?

**Comment by matty1979** [comment]
Sort of, I can get the helm chart to install, but making any options changes are hard for me to understand and I could use better documentation on it.

**Comment by weicongs-amazon** [comment]
thanks. close this issue.
