### ISSUE TITLE
Docker image should provide ability to specify password for the admin user

### ISSUE THREAD

**Issue by untoldone** [opendistro-for-elasticsearch/opendistro-build#201]
Currently `opendistro_security/securityconfig/internal_users.yml` is only read for password hashes on the initial load.

All the documentation to date relies docker containers getting destroyed in-between edits to this file. This is not an expected usage pattern in any commonly used open source project configuration.

The expectation would be that editing this file takes effect after a service restart (or live). At a minimum, I'd expect the documentation around this to be much clearer that the container actually needs to be destroyed for this to take.

Also useful would be a method (or documentation if it already exists) on how to change the admin password after a cluster has been brought up for docker without destroying or stopping the container and related volumes as the docs I've seen seem for outside of docker seem to use tools not present in the docker container.

I would imagine changing a password without downtime would be a common maintenance task for production systems.

**Comment by weicongs-amazon** [comment]
For security feature in production, it doesn't only mean password change. pls take a look at this doc: https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker-security/  
@vrozov @sujithvm pls help to share more security related context if needed.

**Comment by weicongs-amazon** [comment]
close this issue firstly as password change support isn't necessary for production case, since there is a way to provide all of security related configurations. If there is other issue, feel free to reopen
