### ISSUE TITLE
keycloak integration

### ISSUE THREAD

**Issue by sunilvancha** [opendistro-for-elasticsearch/opendistro-build#213]
Hi,

I am looking to integrate opendistro with keycloak.  As per the below URL security plugin can be used to integrate with opendistro. is this available in this helm chart values.yaml or any other separate chart?

https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/openid-connect/

**Comment by weicongs-amazon** [comment]
Hi @sunilvancha you can take a look at the security configuration part in the doc: https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/README.md#security-configuration  by providing your customized file. We never test it before. pls share your result to back to us. Thanks

**Comment by sunilvancha** [comment]
I tried integrating with keycloak but i see below errors after logging into to EFK. 




plugin:opendistro_security@1.7.0.0 | An error occurred during initialisation, please check the logs.
-- | --


Security tab is not completely visible in EFK portal.

Given below is the values.yaml configuration. I have created required secrets for openid.

# Default values for efk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Available parameters and their default values for the efk chart.
{{RELEASE_NAME=${RELEASE_NAME}}}

global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  enabled: true

#opendistro-es values.yaml contents
#https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/opendistro-es/values.yaml
opendistro-es:

  kibana:
    enabled: true
    replicas: 1

    ingress:
      ## Set to true to enable ingress record generation
      enabled: true
      path: /
      hosts:
        - elasticsearch-nonprod.devops.ohlogistics.com
      tls:
        - hosts:
          - elasticsearch-nonprod.devops.ohlogistics.com
    config:
          ## Default Kibana configuration from kibana-docker.
      server.name: kibana
      server.host: "0.0.0.0"
      #server.ssl.enabled: true
      #server.ssl.key: "/usr/share/kibana/certs/kibana-key.pem"
      #server.ssl.certificate: "/usr/share/kibana/certs/kibana-crt.pem"
      # Replace with Elasticsearch DNS name picked during Service deployment
      elasticsearch.hosts: https://{{RELEASE_NAME}}-opendistro-es-client-service:9200
      elasticsearch.ssl.verificationMode: none
      logging.verbose: true
      elasticsearch.username: "kibanaserver"
      elasticsearch.password: "kibanaserver"
      elasticsearch.requestHeadersWhitelist: ["security_tenant", "securitytenant", "Authorization"]
      opendistro_security.multitenancy.enabled: true
      opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
      opendistro_security.readonly_mode.roles: ["kibana_read_only"]
      newsfeed.enabled: false
      telemetry.optIn: false
      telemetry.enabled: false
      #logger.opendistro_security.level: trace
      #logger.opendistro_security.appenderRef.rolling.ref: rolling
      #logger.opendistro_security.appenderRef.rolling_old.ref: rolling_old
      #logger.opendistro_security.additivity: false
      opendistro_security.allow_client_certificates: true
      #elasticsearch.ssl.certificate: "/usr/share/kibana/certs/elk-rest-crt.pem"
      #elasticsearch.ssl.key: "/usr/share/kibana/certs/elk-rest-key.pem"
      #elasticsearch.ssl.certificateAuthorities: "/usr/share/kibana/certs/elk-rest-root-ca.pem"
      #elasticsearch.requestTimeout: 360000

    ## Kibana TLS Config
      #server.ssl.enabled: true
      #server.ssl.key: /usr/share/kibana/certs/kibana-key.pem
      # server.ssl.certificate: /usr/share/kibana/certs/kibana-crt.pem
      # elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/certs/kibana-root-ca.pem

      #opendistro_security.cookie.secure: false
      
      opendistro_security.auth.type: "openid"
      opendistro_security.openid.connect_url: "****"
      opendistro_security.openid.client_id: "*******"
      opendistro_security.openid.client_secret: "**********"

  elasticsearch:
    master:
      enabled: true
      replicas: 1

      persistence:
        enabled: true
        storageClass: vsphere-volumes
        size: 8Gi

    securityConfig:
      enabled: true
      path: "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig"
      configSecret: "security-config"

    data:
      enabled: true
      replicas: 1

      persistence:
        enabled: true
        storageClass: vsphere-volumes
        size: 8Gi

    client:
      enabled: true
      replicas: 1

#fluent-bit values.yaml contents
#https://github.com/helm/charts/blob/master/stable/fluent-bit/values.yaml
fluent-bit:

  backend:
    type: es
    es:
      host: {{RELEASE_NAME}}-opendistro-es-client-service
      port: 9200
      # Elastic Index Name
      index: kubernetes_cluster
      type: flb_type
      logstash_prefix: kubernetes_cluster
      replace_dots: "On"
      logstash_format: "On"
      retry_limit: "False"
      time_key: "@timestamp"
      http_user: "****"
      http_passwd: "*****"
      tls: "on"
      tls_verify: "off"
      # TLS certificate for the Elastic (in PEM format). Use if tls=on and tls_verify=on.
      tls_ca: ""
      tls_debug: 1

  service:
    flush: 1
    logLevel: debug

  input:
    systemd:
      enabled: true

  audit:
    enable: true

  filter:
    mergeJSONLog: false
 
Given below is the  config.yaml
---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    do_not_fail_on_forbidden: true
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      openid_auth_domain:
        description: "Authenticate via Keycloak Identity Provider"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: "****"
            jwks_uri: "*****"
            enable_ssl_client_auth: false
            #pemkey_filepath: "/usr/share/elasticsearch/config/esnode-key.pem"
            #pemcert_filepath: "/usr/share/elasticsearch/config/esnode.pem"
            #pemtrustedcas_filepath: "/usr/share/elasticsearch/config/root-ca.pem"
            enable_ssl: false
            verify_hostnames: false
        authentication_backend:
          type: noop
      kerberos_auth_domain:
        http_enabled: false
        transport_enabled: false
        order: 2
        http_authenticator:
          type: kerberos
          challenge: true
          config:
            krb_debug: false
            strip_realm_from_principal: true
        authentication_backend:
          type: noop
      proxy_auth_domain:
        description: "Authenticate via proxy"
        http_enabled: false
        transport_enabled: false
        order: 3
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: noop
      jwt_auth_domain:
        description: "Authenticate via Json Web Token"
        http_enabled: false
        transport_enabled: false
        order: 4
        http_authenticator:
          type: jwt
          challenge: false
          config:
            signing_key: "base64 encoded HMAC key or public RSA/ECDSA pem key"
            jwt_header: "Authorization"
            jwt_url_parameter: null
            roles_key: null
            subject_key: null
        authentication_backend:
          type: noop
      clientcert_auth_domain:
        description: "Authenticate via SSL client certificates"
        http_enabled: false
        transport_enabled: false
        order: 5
        http_authenticator:
          type: clientcert
          config:
            username_attribute: cn #optional, if omitted DN becomes username
          challenge: false
        authentication_backend:
          type: noop
      ldap:
        description: "Authenticate via LDAP or Active Directory"
        http_enabled: false
        transport_enabled: false
        order: 6
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: ldap
          config:
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: true
            hosts:
            - localhost:8389
            bind_dn: null
            password: null
            userbase: 'ou=people,dc=example,dc=com'
            usersearch: '(sAMAccountName={0})'
            username_attribute: null
    authz:
      roles_from_myldap:
        description: "Authorize via LDAP or Active Directory"
        http_enabled: false
        transport_enabled: false
        authorization_backend:
          type: ldap
          config:
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: true
            hosts:
            - localhost:8389
            bind_dn: null
            password: null
            rolebase: 'ou=groups,dc=example,dc=com'
            rolesearch: '(member={0})'
            userroleattribute: null
            userrolename: disabled
            rolename: cn
            resolve_nested_roles: true
            userbase: 'ou=people,dc=example,dc=com'
            usersearch: '(uid={0})'
      roles_from_another_ldap:
        description: "Authorize via another Active Directory"
        http_enabled: false
        transport_enabled: false
        authorization_backend:
          type: ldap

**Comment by weicongs-amazon** [comment]
@sunilvancha could you help to share the detailed error log of security plugin initialization? it seems to be related to security configurations.

**Comment by weicongs-amazon** [comment]
@sunilvancha do you still have issue? we will close this issue firstly. feel free to reopen
