### ISSUE TITLE
Support Elasticsearch 7.4.0

### ISSUE THREAD

**Issue by sc7565** [opendistro-for-elasticsearch/opendistro-build#23]
Support Elasticsearch 7.4.0

**Comment by sheldonrong** [comment]
@alolita any roadmap on when 7.4.0 would be available?

**Comment by alolita** [comment]
Hi @sheldonrong 7.4 will be right after 7.3.2 which is in progress right now. Stay tuned :-)

**Comment by CodeFreezr** [comment]
We are also very excited about 7.4.x not only because of the CVE Fix. So we are prepared to jump very fast on 7.4. Do you have any due guesses?

**Comment by q2dg** [comment]
Well, there's a 7.5.1 release shipped already ....it seems a neverending race

**Comment by kaumudpa** [comment]
@alolita Any timeline when support for ES 7.4.2 will be available? as mentioned by @q2dg ES 7.5.1 is also publically available!

**Comment by alolita** [comment]
Hi @kaumudpa Open Distro 1.4 support 7.4.2 is in the works. Expect an update in the next couple of weeks. Open Distro 1.5 is right after with 7.5.x support.

**Comment by aetter** [comment]
https://opendistro.github.io/for-elasticsearch-docs/version-history/

**Comment by q2dg** [comment]
Well, I don't want to be a moron, but there's the 7.6.0 version release already.
My main complain isn't about the Open-Distro itself but about its discrete plugins ...I can't install them on last ElasticSearch version. 
The worst is that it's not a current problem...it seems it will be here many time from now in a neverending race...

**Comment by aetter** [comment]
Hi @q2dg, don't worry, it's a common question.

ODFE is a bit like a Linux distro. It takes some time for Linux distros to use the latest version of the kernel. After it releases, distros have to pick it up, test it against their components, make changes for compatibility, build, perform additional testing, etc.

Our project is smaller, so our turnaround time is (hopefully) much faster, but we're always going to lag a little bit behind the latest release. It's pretty rare for new versions of Elasticsearch OSS to include new features -- most of the work occurs in the proprietary codebase now -- so we think waiting for new versions of ODFE before upgrading is worthwhile. Totally understood that some people want to use the absolute latest, though, so we're always working to minimize that lag time.
