### ISSUE TITLE
Add Upgrading Testing for ODFE Distribution Release

### ISSUE THREAD

**Issue by weicongs-amazon** [opendistro-for-elasticsearch/opendistro-build#236]
Add Upgrading testing for new version release. This testing will cover the service installation and check if the service can start up successfully after upgrading.

**Comment by gaiksaya** [comment]
Created a [workflow](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/.github/workflows/check-version-upgrade.yml) that will install the previous version of ODFE for DEB and RPM distribution and check the version upgrade for upcoming version to catch any breaking changes.
