### ISSUE TITLE
Elasticsearch and Kibana build as a Single Image

### ISSUE THREAD

**Issue by vishleshpatel** [opendistro-for-elasticsearch/opendistro-build#26]
As a user, it would be great to have elasticsearch and kibana packaged in a single docker image. so that it can be ran in cloud environment easily with minimal configuration and compute resources where logs can be hosted from cloud services like cloudwatch, etc.

**Comment by alolita** [comment]
Thanks for your suggestion @vishleshpatel

**Comment by weicongs-amazon** [comment]
Thanks for this suggestion. This single image for both of elasticsearch and kibana isn't in our plan currently
