### ISSUE TITLE
KIbana build is failing with no such file or directory

### ISSUE THREAD

**Issue by sachinmsft** [opendistro-for-elasticsearch/opendistro-build#273]
I am building Kibana image and following the steps but getting below error. Am I missing something. ?

~/opendistro-build/kibana/docker# OPENDISTRO_VERSION=0.8.0 ES_VERSION=6.6.2 make build
jinja2 \
  -D artifacts_url=''https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana'' \
  -D version_tag='0.8.0' \
  -D es_version='6.6.2' \
  -D plugins='opendistro-sql-workbench/opendistro-sql-workbench-0.8.0.0.zip opendistro-anomaly-detection/opendistro-anomaly-detection-kibana-0.8.0.0.zip opendistro-security/opendistro_security_kibana_plugin-0.8.0.0.zip opendistro-alerting/opendistro-alerting-0.8.0.0.zip opendistro-index-management/opendistro_index_management_kibana-0.8.0.0.zip' \
  -D build_date='20.06.17' \
  templates/Dockerfile.j2 > build/kibana/Dockerfile;
docker pull centos:7
7: Pulling from library/centos
Digest: sha256:e9ce0b76f29f942502facd849f3e468232492b259b9d9f076f71b392293f1582
Status: Image is up to date for centos:7
docker.io/library/centos:7
pyfiglet -w 160 -f puffy "build: OpenDistroForElasticSearch"; \
docker build -t amazon/opendistro-for-elasticsearch-kibana:0.8.0 \
  -f build/kibana/Dockerfile build/kibana; \
    docker tag amazon/opendistro-for-elasticsearch-kibana:0.8.0 amazon/opendistro-for-elasticsearch-kibana:0.8.0;
 _                _        _
( )            _ (_ )     ( )
| |_    _   _ (_) | |    _| | _
| '_`\ ( ) ( )| | | |  /'_` |(_)
| |_) )| (_) || | | | ( (_| | _
(_,__/'`\___/'(_)(___)`\__,_)(_)

 _____                       ___             _                ___              ___    _                 _              ___                              _
(  _  )                     (  _`\  _       ( )_             (  _`\           (  _`\ (_ )              ( )_  _        (  _`\                           ( )
| ( ) | _ _      __    ___  | | ) |(_)  ___ | ,_) _ __   _   | (_(_)_    _ __ | (_(_) | |    _ _   ___ | ,_)(_)   ___ | (_(_)   __     _ _  _ __   ___ | |__
| | | |( '_`\  /'__`\/' _ `\| | | )| |/',__)| |  ( '__)/'_`\ |  _)/'_`\ ( '__)|  _)_  | |  /'_` )/',__)| |  | | /'___)`\__ \  /'__`\ /'_` )( '__)/'___)|  _ `\
| (_) || (_) )(  ___/| ( ) || |_) || |\__, \| |_ | |  ( (_) )| | ( (_) )| |   | (_( ) | | ( (_| |\__, \| |_ | |( (___ ( )_) |(  ___/( (_| || |  ( (___ | | | |
(_____)| ,__/'`\____)(_) (_)(____/'(_)(____/`\__)(_)  `\___/'(_) `\___/'(_)   (____/'(___)`\__,_)(____/`\__)(_)`\____)`\____)`\____)`\__,_)(_)  `\____)(_) (_)
       | |
       (_)

Sending build context to Docker daemon  18.94kB
Step 1/16 : FROM centos:7
 ---> b5b4d78bc90c
Step 2/16 : ENV ELASTIC_CONTAINER true
 ---> Using cache
 ---> 2d32ca09f69c
Step 3/16 : RUN yum update -y && yum install -y fontconfig freetype && yum clean all
 ---> Using cache
 ---> 3403e41ab5aa
Step 4/16 : WORKDIR /usr/share/kibana
 ---> Using cache
 ---> 8ba5ea26c601
Step 5/16 : ENV PATH=/usr/share/kibana/bin:$PATH
 ---> Using cache
 ---> 2be9fc405ece
Step 6/16 : RUN rm -rf /tmp/plugins && mkdir /tmp/plugins
 ---> Using cache
 ---> 134e9e5d58ad
Step 7/16 : ADD plugins /tmp/plugins/
**ADD failed: stat /var/lib/docker/tmp/docker-builder191021488/plugins: no such file or directory
Error response from daemon: No such image: amazon/opendistro-for-elasticsearch-kibana:0.8.0
Makefile:56: recipe for target 'build' failed**
make: *** [build] Error 1

while downloading plugins. I see below error

/home/sachin/opendistro-build
7.7.1
1.8.1
**Unable to locate credentials. You can configure credentials by running "aws configure".
downloading**

**Comment by peterzhuamazon** [comment]
Hi @sachinmsft those steps requires connections to aws with our credentials.
May I ask the reason you want to build this image yourself?
We have docker images published [here](https://hub.docker.com/r/amazon/opendistro-for-elasticsearch-kibana). Thanks.

**Comment by sachinmsft** [comment]
Hi @peterzhuamazon we want to build the entire open distro stack inhouse.
is there any documentation for that ?

**Comment by peterzhuamazon** [comment]
Sorry @sachinmsft, we currently do not have any documentations.

If you want to build docker image for ODFE in house, you are welcome to download the tar/zip version of ODFE, and create a dockerfile/image for your needs. Thanks.

https://opendistro.github.io/for-elasticsearch-docs/docs/install/tar/

**Comment by sachinmsft** [comment]
is it not possible to build the individuals plugins separately and then create the docker image by installing these plugins ?

**Comment by peterzhuamazon** [comment]
@sachinmsft Can you describe exactly what you want to build?
Are you trying to manually build every plugins by yourself?
If you just want to install plugins individually, check [here](https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/).

**Comment by sachinmsft** [comment]
@peterzhuamazon So requirement is to build each and every components in house so that is the reason I was looking to build every plugins by myself and create the docker image inhouse.

**Comment by peterzhuamazon** [comment]
If you want to build plugins individually by yourself, please check all the plugin repos [here](https://github.com/opendistro-for-elasticsearch).
This build repo is pulling the artifacts that already built from the plugin repos and package them into release candidates.
Please feel free to contact devs from individual plugin repos if you have confusions on building process of individual components. Thanks.

**Comment by peterzhuamazon** [comment]
Close this issue for now and please feel free to reopen it. Thanks.
