### ISSUE TITLE
Support for ppc64le architecture

### ISSUE THREAD

**Issue by junawaneshivani** [opendistro-for-elasticsearch/opendistro-build#280]
Hi All, 

I have been trying to build the dockerized version of elasticsearch on ppc64le architecture. However, what I observed is, there are x86 specific references in the Dockerfile. Is there any alternate way of building elasticsearch locally instead of directly downloading the artifacts from elastic.co ?

https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/elasticsearch/docker/templates/Dockerfile.j2#L25 
https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/elasticsearch/docker/templates/Dockerfile.j2#L67

**Comment by peterzhuamazon** [comment]
Hi @junawaneshivani. Sorry that we currently do not support ppc64le arch.
Our workflow only pulls the oss archive from upstream, and only focus on x86 for now.
However, after a quick search, seems like other sources have provided ppc64le version of the docker images for [ES](https://hub.docker.com/r/ibmcom/elasticsearch-ppc64le/tags) and [Kibana](https://hub.docker.com/r/ibmcom/kibana-ppc64le) on docker hub.

We will put this into the backlog and keep monitoring the activities about other arch support from upstream.

Thank you for your information and suggestions.

**Comment by gerrith3** [comment]
@peterzhuamazon what do you need to be able to support ppc64le?  We are willing to help get this going in any way needed.

**Comment by alolita** [comment]
Hi @gerrith3 thanks for reaching out. It would be great to have ppc64le support but we are currently not resourced to support additional architectures. Perhaps your team would be interested in supporting a ppc64le version of the ODFE distribution, maintain version currency and provide a test suite for all plugin developers to verify that their plugins work. Happy for our team to have a chat with you!

**Comment by gerrith3** [comment]
I think a chat would be excellent.  I can set one up with a couple of IBM players if you would like a phone call, or if there is a slack channel, or just here in the GH issue.  We have interest in both Power and Z (s390x) support across the board and may be able to get things started and figure out where to go from there.  Do you know if there is a good summary of what it would take to create an ODFE distribution?  We can do most of currency with Travis CI, or perhaps at OSL with Jenkins or a VM that can plug into an existing test infrastructure.

**Comment by camerski** [comment]
Hi @junawaneshivani and @gerrith3.

As @alolita mentioned, we are not currently resourced to support additional architectures and will not be able to help with this right now.

If your team is willing to support PowerPC and Z then you could consider making a contribution to the [community repository](https://github.com/opendistro-for-elasticsearch/community) with the required software patches and test suites.

 I'm resolving this issue for now; we can re-open it if and when we are able to provide resources for the project.
