### ISSUE TITLE
Helm: Add support to request specific version of ODFE to Helm chart

### ISSUE THREAD

**Issue by gsmith-sas** [opendistro-for-elasticsearch/opendistro-build#296]
Development progress on the ODFE is moving rapidly ahead: that is great!  But, for some of us, especially those of us embedding ODFE in our own projects, it is difficult to keep up.  As each new release comes out, we must validate that the latest changes do not modify or break any of the functionality we depend on.  In addition, new releases of ODFE come out as they are finished rather than on a set schedule; therefore, we don't know when a new release will suddenly appear and, potentially, break our project.  For example, ODFE 1.8.0 was released while I was sleeping and broke my deployment scripting (due to a file name change) which affected my customers in Asia and Europe before I even got to work.  

To make things easier on us, it would be nice if the Helm chart allowed us to request a specific version.  This would allow for the consistent and repeatable deployment of the same ODFE image over time.  And, this would mean we could validate new releases as time permits without having to worry about the impact on our users.  Obviously, supporting every historical version of ODFE is not possible.  But, perhaps, some defined support policy could be implemented.  For example, maybe the policy could be "_the ODFE chart will support the newest release and two previous ones_".

**Comment by weicongs-amazon** [comment]
Hi @gsmith-sas, feel sorry that new release broke your env. A new release tag will be created for each released version, https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/v1.8.0 . Checking out the repo with the specific tag can be a workaround for your problem. Our team will have a discussion for the long term plan.

**Comment by peterzhuamazon** [comment]
Hi @gsmith-sas since @weicongs-amazon has already provided a solution, we will close this issue for now.
Please feel free to re-open it if you have more questions. We are glad to help with it. Thanks.
