### ISSUE TITLE
Packages for FreeBSD.

### ISSUE THREAD

**Issue by mzs114** [opendistro-for-elasticsearch/opendistro-build#30]
FreeBSD has stock ELK 6, OpenDistro would be a good alternative for it, FreeBSD has OpenJDK 8 and 11 in the stock repositories so getting OpenDistro run on it should be straight forward.

I can help in testing out the packages, the current .tar.gz files are too GNU/Linux specific and won't work without major changes, like the shell scripts to launch the Elasticsearch service.

**Comment by alolita** [comment]
Hi @mzs114 Would you like to contribute these packages to support FreeBSD?

**Comment by mzs114** [comment]
@alolita I would love to volunteer, let me know how can I help. I might be limited by the time I can spend on this, but will try to contribute as mush as I can.

**Comment by koobs** [comment]
@mzs114 One may want to start with notes on where opendistro fails/needs work, and address those items in a "freebsd port", that we could them upstream patches for. 

Most bash/linux'isms in upstream software has example fixes across our ports tree, so its quite rare to have super involved or problems with unknown solutions, modulo *actually* depending on linux specific syscalls/features that requires writing new BSD compatible code.

If you need porting support #freebsd-ports on freenode IRC

Anything we need upstream help/advice with/questions for we can address here

**Comment by weicongs-amazon** [comment]
close this one. use https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/205 to track this feature .
