### ISSUE TITLE
[helm] kibana ingress path syntax

### ISSUE THREAD

**Issue by Hokwang** [opendistro-for-elasticsearch/opendistro-build#307]
Hello.

In case of elasticsearch ingress path,
```
...
{{ $ingressPath := .Values.elasticsearch.client.ingress.path }}
...
          - path: {{ $ingressPath }}
```
https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/7f24dcb310764c0a8e0921f7bd228aa2d23fad19/helm/opendistro-es/templates/elasticsearch/es-client-ingress.yaml#L17-L44

(Actually I don't know why make `$ingressPath` variable in this file)

But kibana's ingress path is different.
```
    {{- range .Values.kibana.ingress.hosts }}
      {{- $url := splitList "/" . }}
...
          - path: /{{ rest $url | join "/" }}
```
https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/7f24dcb310764c0a8e0921f7bd228aa2d23fad19/helm/opendistro-es/templates/kibana/kibana-ingress.yml#L30-L35

We need to change `path:` value to `.Values.kibana.ingress.path` and user should not input `a.com/kibana` style in `host:` value.

**Comment by weicongs-amazon** [comment]
@Hokwang thanks for sharing this finding. I think we should use the same way for both eleasticsearch and kibana. The helm chart is mainly contributed by community. Appreciate a lot if you can make a PR for this change.

**Comment by peterzhuamazon** [comment]
Thanks @Hokwang I am closing this issue as PR #340 is now merged to master.
