### ISSUE TITLE
Sample Docker Compose file 1.9.0 does not work

### ISSUE THREAD

**Issue by davidgarciaMontreal** [opendistro-for-elasticsearch/opendistro-build#329]
As per the following documentation:  https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/ running the docker-compose does not work. After it is launched with the 7.8.0 version the kibana server returns a 503 error code.

statusCode | 500
-- | --
error | "Internal Server Error"
message | "An internal server error occurred."

```bash
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429

docker-compose -version
docker-compose version 1.25.5, build 8a1c60f6

uname -a
Darwin antonios-iMac.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64


```

**Comment by peterzhuamazon** [comment]
Hi @davidgarciaMontreal I have just tested the sample docker-compose file [here](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#sample-docker-compose-file) with 1.9.0.
And I have no issues with kibana. I have tested it on a ubuntu 18.04 on both m4.xlarge and m4.2xlarge instance.

Kibana is able to access on :::5601, I waited 2 minutes for both and am able to reach the dashboard with no issues.

Would you mind sending the docker-compose log to us? So we can debug further based on the logs.

Also, a common issue we face is user has a default vm map count of 65530 thus cause the ES node to fail but KIBANA node to keep running.

sudo sysctl -w vm.max_map_count=262144

Thanks.

**Comment by davidgarciaMontreal** [comment]
@peterzhuamazon could it a problem with the host? I'm running the same version on a macOS High Sierra.
Do you know if it's not supported on macOS system?

**Comment by peterzhuamazon** [comment]
Hello @davidgarciaMontreal Sorry that I missed you are using darwin. 

On the top of the docker page, we have listed "If you run Docker locally, we recommend allowing Docker to use at least 4 GB of RAM in Preferences > Advanced."
![image](https://user-images.githubusercontent.com/65193828/89203148-100d6700-d582-11ea-9510-877f82775269.png)

If you are using docker desktop on macos, kindly change the default 2GB RAM allocation to 4GB here:
![image](https://user-images.githubusercontent.com/65193828/89203055-e5bba980-d581-11ea-9150-6c2fa6bb0bdc.png)
![image](https://user-images.githubusercontent.com/65193828/89203102-fb30d380-d581-11ea-9f9d-39f0a7399273.png)


Then it should work with 2 es + 1 kibana setup.

If you are using an older version of macbook, you can just remove odfe-node2 related settings and create a 1 es + 1 kibana setup, which also works.

Please let me know if you have any other questions, I hope you can get your setup work on macos now.

Thanks.

**Comment by davidgarciaMontreal** [comment]
@peterzhuamazon i will try it this weekend and upload the logs if it fails.
Thanks David

**Comment by davidgarciaMontreal** [comment]
@peterzhuamazon  I read the recommendation but i would not have thought the problem would that. I think i had allocated 2 or 3GB and I was gettting errors related to transport, one elastic search node could not reach the other. I have now increased it to 4GB and it is working as expected. 
Now I wonder if the recommendation should be changed to a must?
Thanks for your help!

**Comment by peterzhuamazon** [comment]
Thanks @davidgarciaMontreal for the suggestions and advices.
We are happy that you have resolved the issues.
This issue will be closed for now. Please feel free to re-open it if you have other questions related to this. Thanks.
