### ISSUE TITLE
Hook up AD Kibana integration tests WITH Security

### ISSUE THREAD

**Issue by ohltyler** [opendistro-for-elasticsearch/opendistro-build#333]
Recent changes have been made to support running the AD Kibana integration tests with security enabled. The command is simply `yarn cy:run-with-security`. Can be added very similarly to the AD Kibana tests with security disabled. 

**NOTE**: Since the infra workflows are pulling tagged versions and the recent changes are not part of any tags, it will obviously fail until we push a new tag.

**Comment by peterzhuamazon** [comment]
Hi @ohltyler, is this working on both Linux and Windows?
Thanks.

**Comment by ohltyler** [comment]
> Hi @ohltyler, is this working on both Linux and Windows?
> Thanks.

Should work fine on Windows, since only difference should be running `cy:run-with-security` rather than `cy:run` - let me know if you have any problems. We don't have a Windows workflow in our current repository so I haven't tested against it.

**Comment by ohltyler** [comment]
One other thing I noticed, looks like there is a typo in the existing `yarn cy:run` commands. When overriding the baseUrl it should be something like `--config baseUrl=<base_url>` rather than `-config baseurl=<base_url>` (should be two `-`'s and `baseUrl` instead of `baseurl`). I think it is working since the default base URL is already http://localhost:5601, but just something to be aware of.

**Comment by peterzhuamazon** [comment]
Thanks @ohltyler.
We are going to assign the task next week and start working on it.
I will fix --config issue in a PR later. Thanks.

**Comment by peterzhuamazon** [comment]
This issue is closed for now as we have added these tests in the workflows.
Thanks!
