### ISSUE TITLE
Upgrade ODFE

### ISSUE THREAD

**Issue by Rulemaster101** [opendistro-for-elasticsearch/opendistro-build#337]
We are upgrading from odfe 1.2.0 to latest version 1.9.0 I need to check what are all the features that are deprecated. I need to install version  1.2.0 in my test bed and check the upgrade process I am unable to install 1.2.0 now . How to do it and what all need to consider before upgrade.

**Comment by peterzhuamazon** [comment]
Hi @Rulemaster101 thanks for contacting us, please kindly tell us which distro you are trying to install and upgrade, what env/os you are working with, and what are the steps you have gone through? Could you clarify more on "unable to install"?

As for the things to consider for upgrade, you can find information [here](https://opendistro.github.io/for-elasticsearch-docs/docs/upgrade/).

**Comment by peterzhuamazon** [comment]
Hi @Rulemaster101 It have been 14 days since my last reply.
This issue will be closed for now.
Please feel free to re-open it if you have any more questions. Thanks.
