### ISSUE TITLE
Elasticsearch container fails when running as non root.

### ISSUE THREAD

**Issue by jkrnak** [opendistro-for-elasticsearch/opendistro-build#34]
When running the container as non root, ie with `securityContext.runAsUser: 1000` the supervisord process was starting up as the passed in user.
This caused supervisord to fail because the `/usr/share/supervisor` directory was owned by root.

**Comment by weicongs-amazon** [comment]
close the issue. feel free to reopen

**Comment by jkrnak** [comment]
Has this been fixed or why did you close?

**Comment by weicongs-amazon** [comment]
@jkrnak we shared some comments in the PR https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/31
We think it's not a good way to grant permissions to all of the users. pls share your idea here.

**Comment by jkrnak** [comment]
@weicongs-amazon sorry, I didn't reply there. I saw the comment and I accept that. 
But currently the es image can't run without root privileges (at least if `opendistro_performance_analyzer` is enabled), which makes it difficult to run on shared (multi tenant) clusters. 

Do you think we could run supervisord with the same UID as the container is running?

**Comment by weicongs-amazon** [comment]
Thanks @jkrnak. Agree with you. This is valid point. We should use the same UID. And there should be an alternative way to start the performance analyzer to avoid the supervisord. Let's sync up with the team firstly.

**Comment by peterzhuamazon** [comment]
We have identify the issue and have a solution proposed.
We are working on it and hopefully will give you an update soon.
Thank you again for your inputs.

**Comment by peterzhuamazon** [comment]
Status Update: this issue still remains open for the upcoming 1.9.0 release.
We plan to push the changes after this release as it requires testings from specific plugin.

**Comment by peterzhuamazon** [comment]
Status Update: This issue is now fixed on both the plugins and the build sides.
Will use this new config in the next releases. This issue will be closed as of now.
Thanks @jkrnak for reporting this and sorry for the delay to get it eventually fixed in ODFE.

**Comment by jkrnak** [comment]
Thank you for fixing it!
