### ISSUE TITLE
Hook up Alerting integration tests WITH Security (admin user)

### ISSUE THREAD

**Issue by skkosuri-amzn** [opendistro-for-elasticsearch/opendistro-build#346]
https://github.com/opendistro-for-elasticsearch/alerting/pull/213
Above PR provides a way to run Alerting integ test against cluster.  Currently, we support using admin user.

`../gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=es-integrationtest -Dhttps=true -Duser=admin -Dpassword=admin`

**Comment by peterzhuamazon** [comment]
Thanks @skkosuri-amzn, we will take a note of this and start adding it to the build workflow.
Thanks very much.

**Comment by gaiksaya** [comment]
Hi @skkosuri-amzn ,

We have added the IT to our distribution workflows. You can check the linked PR. Closing this issue as resolved.
Thanks!
