### ISSUE TITLE
upgrade using yum not working when going from 1.6.0-1 to 1.8.0-1. Getting error Error in PREIN scriptlet in rpm package

### ISSUE THREAD

**Issue by sushovan23** [opendistro-for-elasticsearch/opendistro-build#370]
**Describe the bug**
Getting while doing upgrade from 1.6 to 1.8 using yum.
Following error is seen : 
    "stderr_lines": [
        "Error in PREIN scriptlet in rpm package opendistroforelasticsearch-1.8.0-1.noarch",
        "opendistroforelasticsearch-1.6.0-1.noarch was supposed to be removed but is not!"
    ],

**To Reproduce**
1. Install opendistro 1.6
2. try to upgrade to 1.8 via yum
3. See error

**Expected behavior**
yum upgrade should be able to delete old package and install newer version similarly to other packages.

**Configuration (please complete the following information):**
 - ODFE/Kibana version [ 1.6]
 - Distribution [ RPM,]
 - Host Machine [ Centos7]

**Comment by sushovan23** [comment]
Also tried installing 1.8 in new server and got this error:
```
Error in PREIN scriptlet in rpm package opendistroforelasticsearch-1.8.0-1.noarch
```
I have installed opendistro 1.8 in multiple servers via same automation but never saw this error while doing rpm install. ?

**Comment by peterzhuamazon** [comment]
Hi @sushovan23,

1. I have tried to reproduce the issue but I did not see any error related to "Error in PREIN scriptlet".
    I am using a centos7 clean server.
    Installing 1.8 from scratch.

2. Upgrading from 1.6 to 1.8 requires some changes, please check the details in this docs:
    https://opendistro.github.io/for-elasticsearch-docs/docs/upgrade/1-8-0/

3. Also, please kindly check this issue, when you try to upgrade to a non-latest version ODFE.
    https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/341

Please let me know if you have any other questions.

Thanks.

**Comment by sushovan23** [comment]
Hi. 
I have gone through the docs. Changes for 1.8 are required when going from 1.7 to 1.8 
I'm going from 1.6 to 1.8 and hence the `anomaly-detector` remove isn't needed. I was able to upgrade using the yum update command. 
But it is concerning that suddenly yum install would fail for upgrade and new installs in that short amount of time.

**Comment by sushovan23** [comment]
Regarding previous versions installs - I had downloaded all rpms which came with 1.8 when it was latest version and kept in our own repo so we can install it without internet reaching outside. 
So i am installing all packages and as mentioned it used to work fine but suddenly saw the error yesterday in that time frame. Not sure why this would be failing. I will do more tests on fresh installs. Upgrade is working as I have tested multiple times now.

**Comment by peterzhuamazon** [comment]
Hi @sushovan23 I just test again, and I also get a connection issues like this:
```
Downloading packages:
opendistro-index-management-1. FAILED                                                                                                            0% [                                                                                                                                       ]  0.0 B/s |    0 B  --:--:-- ETA
https://d3g5vo6xdbdb9a.cloudfront.net/yum/noarch/opendistro-index-management-1.6.0.0-1.noarch.rpm: [Errno 14] curl#56 - "TCP connection reset by peer"                                                                                                                                      ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
opendistro-alerting-1.6.0.0-1. FAILED
https://d3g5vo6xdbdb9a.cloudfront.net/yum/noarch/opendistro-alerting-1.6.0.0-1.noarch.rpm: [Errno 14] curl#56 - "TCP connection reset by peer"   0% [                                                                                                                                       ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
```

Seems like some internet hiccup, I retried and it works again.

Sorry about the inconvenience, is your issue completely resolved for now?

Thanks.

**Comment by peterzhuamazon** [comment]
> Regarding previous versions installs - I had downloaded all rpms which came with 1.8 when it was latest version and kept in our own repo so we can install it without internet reaching outside.
> So i am installing all packages and as mentioned it used to work fine but suddenly saw the error yesterday in that time frame. Not sure why this would be failing. I will do more tests on fresh installs. Upgrade is working as I have tested multiple times now.

It is weird that this would happen in your own repo, was thinking of connectivity issues. Hopefully it is resolved.

**Comment by sushovan23** [comment]
Looks like it was more of connectivity issues. So I have all rpms in my own repo. but it still tries to download this which was failing yesterday -        
 "Fetching kNN library",
  "--2020-09-02 20:28:21--  https://d3g5vo6xdbdb9a.cloudfront.net/downloads/k-NN-lib/libKNNIndexV1_7_3_6.zip"

this is indeed related to network then. any way I can provide this from within my network?

**Comment by sushovan23** [comment]
so my issue is solved for now but as we found out the connectivity issues to the download url is not best for automation. any suggestions on how to handle the zip/so library download

**Comment by peterzhuamazon** [comment]
Hi @sushovan23 KNN is fixed in 1.9.0. https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/274
We have acknowledge the issues with KNN Lib downloading with a preinstall script.
Please consider using 1.9.0 for this fix.

Thanks.

**Comment by peterzhuamazon** [comment]
As if 1.9.0 knnlib in RPM will distribute in a standalone rpm instead of a zip.

**Comment by sushovan23** [comment]
Thanks I will create a task for me to handle this. I will be closing this issue since I already have all other rpms I will just take new 1.9 rpms and update my repo.
