### ISSUE TITLE
Remove elasticsearch.ssl.transport.enabled:false/true as it has no effect now

### ISSUE THREAD

**Issue by dmpe** [opendistro-for-elasticsearch/opendistro-build#379]
In the helm chart readme, 
https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm
is no longer relevant because transport tls is always enabled.

**Comment by peterzhuamazon** [comment]
Hi @dmpe thanks for pointing this out.
The original change to disable this parameter is here: https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/53

As of now, the HELM section is actively maintained by the community members.
Would you mind create a PR for this change in documentation? We would be very much appreciated.
Thanks.
