### ISSUE TITLE
Automated security audit / CVE detection 

### ISSUE THREAD

**Issue by peterzhuamazon** [opendistro-for-elasticsearch/opendistro-build#386]
Integrate GitHub security app to the public repo's to block PR’s with vulnerabilities. This would automatically block the code merge that has vulnerabilities.

**Comment by vrozov** [comment]
It will be good to have security audit (CVE detection) for every PR request not just for the release.

**Comment by peterzhuamazon** [comment]
This is complete with @sreekarjami adding WhiteSource and CodeQL to our repo.
