### ISSUE TITLE
Elasticsearch and Opendistro in the same cluster

### ISSUE THREAD

**Issue by mosajjal** [opendistro-for-elasticsearch/opendistro-build#39]
Hi,

I think the title of my question is pretty self explanatory. I'm keen to know if an Opendistro 1.3 (7.3.2) node can co-exist with a current ES cluster and the migration from ES to Opendistro could be done on a node-by-node basis. 

Thanks,

**Comment by DandyDeveloper** [comment]
@mosajjal 
1. Can this co-exist?
From a chart / deployment perspecitve, yes. A large part of this chart is reinvented and has no relationship to the other available Elasticsearch based charts. I'd recommend namespacing your releases, just to be safe, but there should be no direct overlap between them.

2. Can the migration be done on a node-by-node basis? 
What do we mean by migration here? There's a lot of underlining changes that might impact a direct node by node migration, in theory it'll work, but you really have to know what you're doing.

**Comment by DandyDeveloper** [comment]
I've just noticed this is also a much older question, sorry. I am just taking part in discussions post the merge of the Helm chart.

**Comment by weicongs-amazon** [comment]
close it. feel free to reopen if you still have issue
