### ISSUE TITLE
[ODFE] Python 2.7.x on Docker images

### ISSUE THREAD

**Issue by devops-42** [opendistro-for-elasticsearch/opendistro-build#393]
Hi,

**Query**
I wonder why Python in version 2.7.5 is shipped with the Docker images for odfe-kibana/elasticsearch. Is it possible to remove Python, If it is not mandatory for running the ODFE stack? If used, is it possible to upgrade it to a supported version?

Thanks in advance for more information!

Cheers!

**Comment by peterzhuamazon** [comment]
Hi @devops-42, we are using centos7.7.1908 as the base of the docker distro.
The package manager YUM is depended on python2, thus it is there by default.
Version 2.7.5-88.el7 is the latest python2 version available on centos 7 repo, thus is the version we shipped with our latest docker releases.

We currently have no plans to move to a centos8.x base, which uses dnf with C/C++ code base.

Please let me know if you have more questions.

Thanks.

**Comment by devops-42** [comment]
Hi Peter,

thanks for your detailed answer. I close this issue.

Cheers!
