### ISSUE TITLE
Security Plugin Release v1.9.0.2 in official Docker image

### ISSUE THREAD

**Issue by mradman-tildeloop** [opendistro-for-elasticsearch/opendistro-build#395]
Hello and thank you for the awesome work on ODFE,
the new security features seem to be missing from the [official Docker image](https://hub.docker.com/r/amazon/opendistro-for-elasticsearch/tags). 
When can we expect it to be added?

**Comment by camerski** [comment]
Hi @mradman-tildeloop,

We are currently working on the 1.10.x series which will have the latest versions of all supported plugins. We currently have no plans for any more releases in the 1.9 series.

Thanks,
Cameron.

**Comment by hardik263** [comment]
Thanks @camerski for such a prompt reply. Would you be able to give us an ETA for the first 1.10.x series ? Is it planned before the trace analytics release i.e Nov or would it be sooner ? Many thanks !
