### ISSUE TITLE
v1.0.0 changes missing?

### ISSUE THREAD

**Issue by weand** [opendistro-for-elasticsearch/opendistro-build#4]
Hi, 

is it correct, that opendistro-build repo misses changes for 1.0.0?

Regards
Andreas

**Comment by alolita** [comment]
Hi @weand We're in the process of pushing the build scripts for 1.0.0 :-) Will update on thread! Thanks for your patience.

**Comment by alolita** [comment]
Hi @weand The build scripts have now been updated for 1.0.0. Please feel free to open another issue if you have any suggested improvements or find any bugs.
