### ISSUE TITLE
[Kubernetes / Docker Swarm] Liveness Probe / Readiness Probe / Healthcheck

### ISSUE THREAD

**Issue by placaze** [opendistro-for-elasticsearch/opendistro-build#423]
**Query**
What's the best why to add a liveness probe & readiness probe for an Elasticsearch deployment of OpenDistro ES? Or what's the best why to configure a healthcheck for a Docker Swarm deployment of OpenDistro ES?

Is there an healthcheck API that can be checked without authentification? Or is there a script/binary in the Docker image?

I read there is a `readiness-probe-script.sh` upstream but I can't find it in OpenDistro: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-readiness.html

I think it can be improved in the Helm chart: https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/opendistro-es/values.yaml#L251

Thanks!

**Comment by peterzhuamazon** [comment]
Hi @placaze,
As of now, helm chart is actively maintained by community members.
Would you consider creating a PR to add / improve this feature?
It would be very helpful to everyone that uses helm.

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @placaze it has been 7 days since your last comment.
Please feel free to re-open the issue if you have more related questions.
Thanks.
