### ISSUE TITLE
Helm: Add option for deploy cluster with master\data\ingest roles in one statefulset 

### ISSUE THREAD

**Issue by everythings-gonna-be-alright** [opendistro-for-elasticsearch/opendistro-build#433]
If i want create elasticsearch for small kubernetes cluster i don't need separate all components to dedicated pods. It take too much resources.
I propose to add option for deploy elasticsearch as only one statefulset

**Comment by camerski** [comment]
Hi @everythings-gonna-be-alright,

Thanks for the suggestion!

The Helm chart is actively maintained by community members. Would you consider creating a PR with this request? It would be very helpful.

Thanks.
