### ISSUE TITLE
Helm: When using a custom kibana.config it can't connect to elasticsearch anymore

### ISSUE THREAD

**Issue by JustDoItSascha** [opendistro-for-elasticsearch/opendistro-build#470]
When I don't use the kibana.config option, the server retrieves the following kibana.yml:

```
---
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# Description: 
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
elasticsearch.hosts: https://localhost:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

# Use this setting if you are running kibana without https
opendistro_security.cookie.secure: false

newsfeed.enabled: false
telemetry.optIn: false
telemetry.enabled: false
```

But when I use a custom config, only my config parameter is used, the default ist overwritten, so nothing works. But even when I try to copy the automatic generated config in the config params, kibana says that https://localhost:9200 is not reacheable. Also I'm wondering how it can work when the hosts parameter is https://localhost:9200, shouldn't it be something else?

**And wouldn't it be nice if we could use an "additional config" property?**

**Comment by sreekarjami** [comment]
Hi @JustDoItSascha ,
Thanks for raising the issue. The host parameter should be similar to https://odfe-node1:9200, based on which node the Kibana is running.  Will look into it more and inform.

**Comment by sreekarjami** [comment]
Hi,
I have tried recreating the issue, but I am able to access the Kibana using the node name. Can you please try similarly on your end and inform if the issue still exists.

**Comment by JustDoItSascha** [comment]
Hi, have you tried to use a custom kibana.config without setting the hosts environment? Because this was causing the issue on my side...

**Comment by sreekarjami** [comment]
Hi @JustDoItSascha ,
I tried with the custom kibana.config and faced similar issue. If you were able to find a fix, please open a PR and we will review. Otherwise we will inform once a fix is available. 

Thanks again for your contribution to the community.

**Comment by sreekarjami** [comment]
Hi @JustDoItSascha ,
As informed in my earlier response. Please open a PR if you are able to fix the issue or we will inform once we provide a Fix. I am closing this issue, as the Fix might not be available in the next immediate release. 

Thanks for your contribution.
