### ISSUE TITLE
Update the AD Integration Test command for release workflows

### ISSUE THREAD

**Issue by weicongs-amazon** [opendistro-for-elasticsearch/opendistro-build#476]
The integration test command for AD plugin need be changed for 1.12.0 release.

The previous one: 
`./gradlew :integTestRunner --tests "com.amazon.opendistroforelasticsearch.ad.rest.*IT" --tests "com.amazon.opendistroforelasticsearch.ad.e2e.*IT" -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="es-integrationtest"
`

It should be changed to:
`
./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="es-integrationtest"
`

**Comment by gaiksaya** [comment]
Hi @weicongs-amazon 

Is the above command same for AD with security with ```-Dhttps=true -Duser=admin -Dpassword=admin``` in addition to that?

**Comment by weicongs-amazon** [comment]
yes. but we can't test it now since security plugin artifact isn't available yet.

**Comment by gaiksaya** [comment]
Cool. Let me know if you need to make changes on infra side. I'll add you as reviewer once the PR is raised.
Thanks!
