### ISSUE TITLE
Update the AD Kibana plugin workflows

### ISSUE THREAD

**Issue by ohltyler** [opendistro-for-elasticsearch/opendistro-build#480]
**Change 1** (**NOTE:** this issue applies to all Kibana plugins using cypress for their integration tests)

Since GitHub actions has deprecated the use of `set-env`, the old version of the Cypress action (`cypress-io/github-action@v1`) breaks the workflows.

All calls to this old action need to be updated to any version >= 2.3.1. For example, the issue will be fixed if using the current latest version:
```
uses: cypress-io/github-action@v2.5.0
```

**Change 2**
Since it is necessary to change the built zips to a new naming convention using camelcase, all references to the zip files and unzipped plugin names will need to be changed. For AD Kibana, the following changes will need to be made:

Zip references:
`opendistro-anomaly-detection-kibana-$plugin_version.zip` -> `opendistroAnomalyDetectionKibana-$plugin_version.zip`

AD plugin references:
`opendistro-anomaly-detection-kibana` -> `opendistroAnomalyDetectionKibana`

Thanks!

**Comment by gaiksaya** [comment]
Addressed **Change 1** in this PR https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/482

**Change 2 is being taken care of by @peterzhuamazon **

**Comment by peterzhuamazon** [comment]
As we discussed **change 2** is finalized with Kibana Plugin Owners.
```
All kibana plugins will change their names to camel cases, so ./bin/kibana-plugin install would work in 7.10.0.
New naming convention format:
opendistro<CamelCasePluginNames>Kibana-<4Digit Plugin Version>.zip

Kibana Naming Convention:
------
opendistroAlertingKibana-1.12.0.x.zip
opendistroAnomalyDetectionKibana-1.12.0.x.zip
opendistroGanttChartKibana-1.12.0.x.zip
opendistroIndexManagementKibana-1.12.0.x.zip
opendistroNoteboooksKibana-1.12.0.x.zip
opendistroQueryWorkbenchKibana-1.12.0.x.zip
opendistroReportsKibana-1.12.0.x.zip
opendistroSecurityKibana-1.12.0.x.zip
opendistroTraceAnalyticsKibana-1.12.0.x.zip
```

Thanks.

**Comment by ohltyler** [comment]
@peterzhuamazon we will still need to change the references in our specific workflow as specified above, otherwise the tests will still fail. You can refer to the changes in the `e2e-tests-workflow.yml` in [this PR](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/pull/329) for the changes in our plugin repo.
