### ISSUE TITLE
Optimise dependency tree for release

### ISSUE THREAD

**Issue by tristancrockett** [opendistro-for-elasticsearch/opendistro-build#51]
As per this comment > https://discuss.opendistrocommunity.dev/t/rpm-packages-dependencies-issues/1105/2

Can the dependency trees for distro's be optimised before release? As ongoing patching becomes an issue on rpm distros. This happens on brand new, fresh installs.

**Comment by alolita** [comment]
Hi @tristancrockett Thanks for raising this issue. Yes they should be optimized. As users migrate from earlier versions of Open Distro to the latest version, dep trees for each version need to be set up.

**Comment by weicongs-amazon** [comment]
Currently, the supported elasticsearch OSS  version is listed in our release notes. And for any breaking changes in new version, a new official doc is created, see the example: https://opendistro.github.io/for-elasticsearch-docs/docs/upgrade/1-8-0/  https://opendistro.github.io/for-elasticsearch-docs/docs/upgrade/1-0-0/

**Comment by peterzhuamazon** [comment]
To avoid future confusions, I have added the notes as breaking changes to 1.0.0 and 1.8.0 release notes.
https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/243
Thanks.
