### ISSUE TITLE
Where can I find a docker image of opendistro for ARM platform?

### ISSUE THREAD

**Issue by Grety** [opendistro-for-elasticsearch/opendistro-build#529]
It seems now impossible to launch this build on ARM or M1 platforms. Kindly advise

**Comment by peterzhuamazon** [comment]
Hi @Grety we are in the process of getting a ARM64 build out soon.
Please stay tuned as we will share more information on our roadmap here:
https://github.com/orgs/opendistro-for-elasticsearch/projects/3

**Comment by peterzhuamazon** [comment]
We will close this issue for now as we will release ARM64 version.

**Comment by Grety** [comment]
@peterzhuamazon thanks for mentioning the roadmap. Kindly, is it theoretically possible to make the build on my own? As I am interested in arm32 architecture. Besides, I think apple chip will grow in popularity

**Comment by peterzhuamazon** [comment]
We are still in the process of code changes to make ARM64 release possible. As of now, the answer is no.
Once we release ARM64 you should be able to find the code in our repo, tho it would have dependencies on our own AWS accounts.
As for apple, we are also working on possible releases, play stay tuned.

Thanks.
