### ISSUE TITLE
Opendistro apt repos have multiple issues

### ISSUE THREAD

**Issue by adiospeds** [opendistro-for-elasticsearch/opendistro-build#534]
Hello
 
1.
I was trying to setup a Jfrog Remote artifactory repository in our organisation and was unable to do so. It looks like there is some issue with the `https://d3g5vo6xdbdb9a.cloudfront.net/apt/`
We have been able to setup all other kinds of external apt repos and have been using artifactory for a number of years now, so it doesn’t look like any issue with artifactory settings.
The url https://d3g5vo6xdbdb9a.cloudfront.net/apt/ if accessed via browser returns Access denied S3 page. I assume the permissions on these folders/objects should be recursively set to publicly browsable (may b allowing listing of objects/files shud fix this issue - not sure about this fix, but I can test.)

Note: We are able to use the repo on our machines by pointing to https://d3g5vo6xdbdb9a.cloudfront.net/apt/ in source.list however not able to set Remote repo in artifactory. Please fix the permissions on the repo folders.

2. 
Also a completely seperate minor issue : I inspected the contents of https://d3g5vo6xdbdb9a.cloudfront.net/apt/dists/stable/main/binary-amd64/Packages
and found the the Homepage link mentioned in the description of all the packages gives a 404. `https://opendistro.github.io/elasticsearch/downloads`
![image](https://user-images.githubusercontent.com/8983446/87540500-6db63e00-c6bd-11ea-8646-630439c43d4f.png)

**Comment by peterzhuamazon** [comment]
Hello @adiospeds,
1. We dont give access to list objects in the S3 bucket for apt repo. Please try using apt download commands to create your own local repo: `apt-get download $PKG` or `apt download $PKG`
2. I believe we have corrected that link to https://opendistro.github.io/for-elasticsearch/downloads.html

Please let me know if there is any more questions.
Thanks.

**Comment by adiospeds** [comment]
Hello @peterzhuamazon

I get this part.. That's what we are doing right now. But this will add an additional task for us to download the repo contents manually everytime there is a new version. (if automated still a job to maintain). 

We use Jfrog Artifactory inside our infra which has the ability to sync repos from the internet and cache them after first download. The cache helps us serve our intranet faster and incase of external repo outages, plus saves us when packages go missing from external repos.

I am sure a lot of orgs use similar intranet caching services and not having a standard debian repo for opendistro packages is stopping us from achieving this goal. 

I hope you understand the actual problem that I am trying to state here. Trying to serve opendistro deb pkgs over an s3 solution is probably breaking the way people can cache the packages and it would be better if they are served in a more user friendly way( allowing directory browsing which is a standard practice when hosting deb pkgs in public repos)

**Comment by peterzhuamazon** [comment]
Hi @adiospeds we dont have the plan to expose/list the entire folder at this point of time due to security concerns.
If you have a specific use case of this, please let us know and we will look into it later.

Thanks.

**Comment by adiospeds** [comment]
Nope - Jfrog artifactory not working with this repo was my only issue. If dir listing cant be enabled rite now for opendistro i'll have to find some other way to get it working. This can be closed
