### ISSUE TITLE
default kibana.yml using elasticsearch.url instead of elasticsearch.hosts

### ISSUE THREAD

**Issue by armijnhemel** [opendistro-for-elasticsearch/opendistro-build#536]
the default kibana.yml in opendistroforelasticsearch-kibana-1.0.0-1.x86_64 (installed on Fedora 30) says:

elasticsearch.url: https://localhost:9200

which should be:

elasticsearch.hosts: https://localhost:9200

to make it work with Elasticsearch 7.0.1. The Docker file seems to overwrite this, but when you are not using the Docker file, but installing it from a package (like I do), then this is not automatically changed.

**Comment by peterzhuamazon** [comment]
Hi @armijnhemel this is already fixed here:
https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/kibana/docker/build/kibana/config/kibana.yml#L20

Thanks.
