### ISSUE TITLE
Kubernetes Azure implementation

### ISSUE THREAD

**Issue by tolahs** [opendistro-for-elasticsearch/opendistro-build#540]
Hi , Thanks for perfect job. I need help for kubernetes azure implementation. I I tried but can't.
Do you think , or plan for azure.

**Comment by peterzhuamazon** [comment]
Hi @tolahs please provide more details on this issue.
I am not really sure what happens, but our docker release should run on all major cloud providers servers.

Please refer to our docs if you have more questions:
https://opendistro.github.io/for-elasticsearch-docs/docs/install/

**Comment by hari819** [comment]
we use it in AKS , without any issue ,kudos to opendistro.
Including TLS1.2 with openid/oauth integration to Azure AD

**Comment by peterzhuamazon** [comment]
Hi @tolahs it has been 8 days since we last talk.
We will close this issue for now, please feel free to re-open it.

Thanks.
