### ISSUE TITLE
README refers to previous version and Helm 3 issue with '--name'

### ISSUE THREAD

**Issue by samarthya** [opendistro-for-elasticsearch/opendistro-build#548]
With [helm 3](https://helm.sh/docs/intro/using_helm/#helm-install-installing-a-package) the name is part of the install command and no longer with the `--name`

The reference provided in the [readme](https://github.com/opendistro-for-elasticsearch/community/tree/master/open-distro-elasticsearch-kubernetes/helm#tldr) refers to the previous version as the option `--name` is there.

For helm version 3.3.0
 
```
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}
```

If you execute the steps mentioned in [readme](https://github.com/opendistro-for-elasticsearch/community/tree/master/open-distro-elasticsearch-kubernetes/helm#tldr) it will yield in error.

```bash
helm install --name opendistro opendistro-es-1.9.0.tgz 
Error: unknown flag: --name
```

**Comment by peterzhuamazon** [comment]
Thanks @samarthya we have updated the documentation.
Also, please refer to this doc in our official website docs for latest updates:
https://opendistro.github.io/for-elasticsearch-docs/docs/install/helm/

Will close this issue for now, please feel free to re-open if you have any other related questions.

Thanks.
