### ISSUE TITLE
Forked Elasticserach/Kibana post 7.11.0 with Apache 2.0 

### ISSUE THREAD

**Issue by kaiwalyajoshi** [opendistro-for-elasticsearch/opendistro-build#571]
Given Amazon's announcement to fork [Elasticsearch](https://aws.amazon.com/blogs/opensource/stepping-up-for-a-truly-open-source-elasticsearch/). When can we start to see [elasticsearch](https://github.com/elastic/elasticsearch), kibana and other Apache 2.0 licensed repositories hosted under this Github Org?

Along those lines when will the build tooling be updated to host artifacts away from [elastic.co](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/52929dad2062041b701430f65ec82f74b9a11986/elasticsearch/linux_distributions/opendistro-tar-build.sh#L62)

**Comment by bbarani** [comment]
@kaiwalyajoshi ,Thanks for your question. As mentioned in [AWS Open Source blog post](https://aws.amazon.com/blogs/opensource/stepping-up-for-a-truly-open-source-elasticsearch/), we will publish new GitHub repositories in the next few weeks.

**Comment by stockholmux** [comment]
@kaiwalyajoshi To echo what @bbarani said, the timeline is "weeks." I don't think we can commit to a firmer timeline than that, but know it's as fast as possible. 

The way the current codebase is structured & licensed requires more than casual forking as we have to make sure we don't have _any_ non-Apache 2.0 code in the builds (it's intermingled with non-free licenses). Then adapting builds and tests also take time. The road is long but manageable.

We'll be posting to the [Open Distro forum](https://discuss.opendistrocommunity.dev/) and the [Open Distro website](https://opendistro.github.io/for-elasticsearch/) with updates on the process.

**Comment by bbarani** [comment]
@kaiwalyajoshi , I am closing this issue now. Feel free to re-open it if you need more information.
