### ISSUE TITLE
Hook up integration test for Security plugin

### ISSUE THREAD

**Issue by cliu123** [opendistro-for-elasticsearch/opendistro-build#573]
Request adding integration test for Security plugin to the build workflow

Assumption:
With security: Elasticsearch is running at http://localhost:9200

Step to run the test:

Start Elasticsearch server with Security plugin
In the ES directory, run command in below to install Demo Certificate
`sh plugins/opendistro_security/tools/install_demo_configuration.sh`

In the plugin directory (security/), run command in below to start the integTests
`mvn -X -Dtest=IntegrationTests test`

**Comment by gaiksaya** [comment]
Hi @cliu123 ,

I am working on adding the above integration test to our workflows. Looks like tests are failing on ARM64. 
`[ERROR] Failed to execute goal on project opendistro_security: Could not resolve dependencies for project com.amazon.opendistroforelasticsearch:opendistro_security:jar:1.13.1.0: Could not find artifact io.netty:netty-tcnative:jar:linux-aarch_64:2.0.25.Final in central (https://repo.maven.apache.org/maven2) -> [Help 1]`
More details here: https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1974584074?check_suite_focus=true
