### ISSUE TITLE
Data Prepper 0.7.1-alpha patch release

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/opendistro-build#587]
Release:

Data Prepper will have a patch release on the earlier released 0.7.0-alpha. This [patch](https://github.com/opendistro-for-elasticsearch/data-prepper/pull/290) allows data prepper to send data to Amazon Elasticsearch domains. This release is planned for Feb 8th. The required artifacts and repo tags will be provided to the opendistro release team before Feb 5th.

**Comment by peterzhuamazon** [comment]
Thanks @kowshikn we will start working on it once we get the staging artifacts.

**Comment by kowshikn** [comment]
@peterzhuamazon 

- The artifacts are now available in the S3 bucket `artifacts.dataprepper.amazon.com`

```
2021-02-01 14:22:45   73863638 opendistroforelasticsearch-data-prepper-0.7.1-alpha-linux-x64.tar.gz
2021-02-01 14:23:30   73892039 opendistroforelasticsearch-data-prepper-0.7.1-alpha-linux-x64.zip
2021-02-01 14:24:02   73863610 opendistroforelasticsearch-data-prepper-0.7.1-alpha-macos-x64.tar.gz
2021-02-01 14:25:48   73892026 opendistroforelasticsearch-data-prepper-0.7.1-alpha-macos-x64.zip
2021-02-01 14:23:00  269223740 opendistroforelasticsearch-data-prepper-jdk-0.7.1-alpha-linux-x64.tar.gz
2021-02-01 14:23:37  269574521 opendistroforelasticsearch-data-prepper-jdk-0.7.1-alpha-linux-x64.zip
2021-02-01 14:24:46  266538923 opendistroforelasticsearch-data-prepper-jdk-0.7.1-alpha-macos-x64.tar.gz
2021-02-01 14:25:58  267001892 opendistroforelasticsearch-data-prepper-jdk-0.7.1-alpha-macos-x64.zip
```

- The release has been tagged for docker release https://github.com/opendistro-for-elasticsearch/data-prepper/tree/0.7.1-alpha

**Comment by peterzhuamazon** [comment]
Thanks @kowshikn will work on it and get back to you once ready.

**Comment by peterzhuamazon** [comment]
We have complete the staging with artifacts and docker images, will wait for @kowshikn to validate and confirm.

**Comment by kowshikn** [comment]
@peterzhuamazon Thanks for the work and I will go ahead and test the staged artifacts and docker images. As mentioned offline the release has been pushed to Feb 16th/Feb 17th. I will update here once its confirmed.

**Comment by kowshikn** [comment]
@peterzhuamazon , I validated the staged artifacts. Can you please go ahead with production steps. The release is planned for Feb 16th.

**Comment by peterzhuamazon** [comment]
Thanks @kowshikn.

**Comment by peterzhuamazon** [comment]
The Data Prepper Team has confirmed that prod release artifacts are good. This task is complete.
Thanks.


S3/Cloudfront Prod:
https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistroforelasticsearch-data-prepper/opendistroforelasticsearch-data-prepper-jdk-0.7.1-alpha-linux-x64.tar.gz
https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistroforelasticsearch-data-prepper/opendistroforelasticsearch-data-prepper-jdk-0.7.1-alpha-linux-x64.zip
https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistroforelasticsearch-data-prepper/opendistroforelasticsearch-data-prepper-jdk-0.7.1-alpha-macos-x64.tar.gz
https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistroforelasticsearch-data-prepper/opendistroforelasticsearch-data-prepper-jdk-0.7.1-alpha-macos-x64.zip
https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistroforelasticsearch-data-prepper/opendistroforelasticsearch-data-prepper-0.7.1-alpha-linux-x64.tar.gz
https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistroforelasticsearch-data-prepper/opendistroforelasticsearch-data-prepper-0.7.1-alpha-linux-x64.zip
https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistroforelasticsearch-data-prepper/opendistroforelasticsearch-data-prepper-0.7.1-alpha-macos-x64.tar.gz
https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistroforelasticsearch-data-prepper/opendistroforelasticsearch-data-prepper-0.7.1-alpha-macos-x64.zip

Docker Prod:
docker pull amazon/opendistro-for-elasticsearch-data-prepper:latest
docker pull amazon/opendistro-for-elasticsearch-data-prepper:0.7.1-alpha
