### ISSUE TITLE
Kibana Lens visualisation missing from latest release

### ISSUE THREAD

**Issue by tw-ayush** [opendistro-for-elasticsearch/opendistro-build#594]
Kibana announced that the kibana 7.10.0 will have lens visualisation generally available which is missing from the opendistro 1.12.0 release (built on top of es v7.10.0).

https://www.elastic.co/blog/kibana-lens-now-generally-available

**Comment by gaiksaya** [comment]
Hi @tw-ayush ,

Looks like the above feature you mentioned is not part of kibana-oss. Hence, its not bundled with ODFE.
Closing this issue.

Please feel free to repoen.

Thanks!
