### ISSUE TITLE
Hook up integration test for Alerting Kibana plugin

### ISSUE THREAD

**Issue by tlfeng** [opendistro-for-elasticsearch/opendistro-build#600]
Request adding integration test for Alerting Kibana plugin to the build workflow with and without security

**Assumption:** 
With security: Elasticsearch is running at http://localhost:9200, Kibana is running at http://localhost:5601
Without security: Elasticsearch is running at https://localhost:9200, Kibana is running at http://localhost:5601

**Step to run the test:**
1. Start Elasticsearch server with Alerting plugin
2. Start Kibana server with Alerting Kibana plugin
3. (Wait for enough time to make sure Kibana server fully started)
4. In the plugin directory (`kibana/plugins/alerting-kibana-plugin`), run command in below to start the Cypress test

With security: `yarn run cypress run --env security_enabled=true`
WIthout security: `yarn run cypress run`

A successful workflow run in Alerting Kibana plugin repo, without security enabled: 
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/actions/runs/489045146
(A test failure is expected when running against Alerting Kibana plugin v1.12.0.2)
The PR to support running Cypress test in ODFE cluster with security enabled for Alerting Kibana plugin:
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/pull/235

**Comment by gaiksaya** [comment]
Hi @tlfeng,

I am working on this issue. However while doing so looks like the the non security tests are working well but for security test it failing. I am testing with `1.13.0`.
Please find the below test runs for alerting kibana plugin with security:
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1931065268?check_suite_focus=true
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1931401599?check_suite_focus=true

Please let us know if you have any update to resolve it. Till then I'll work on adding non-security tests.
Thanks!

**Comment by tlfeng** [comment]
Thank you for informing me the result of the workflow runs. Let me take a loot at the failures.

**Comment by tlfeng** [comment]
Seems the test failure is caused by this modal appears on the top, I'm going to find solution for it.
<img width="997" alt="select your tenant - modal 7 10 2" src="https://user-images.githubusercontent.com/78394866/108813414-d758cd80-7565-11eb-91ad-1b2c38d5c28b.png">

**Comment by gaiksaya** [comment]
Sure @tlfeng . Let me know when you fix it or have an update.
Thanks!

**Comment by bbarani** [comment]
@tlfeng , Any update on this issue?

**Comment by tlfeng** [comment]
Hi @bbarani, sorry that I haven't took much time on finding the solution. I will try to find the fix in this week, including checking how other plugins deal with it.

**Comment by tlfeng** [comment]
Hi @gaiksaya,
Sorry for the delay.
The fix of the test failure in ODFE 1.13 was merged, and please help me verify the test result when you have time.
Thank you!

**Comment by gaiksaya** [comment]
Hi @tlfeng ,

Thank you for fixing it. I have created the PR to add the tests in our workflows.

**Comment by tlfeng** [comment]
Thank you for your rapid action! 👍👍 @gaiksaya
