### ISSUE TITLE
Add S3 bucket and CloudFront URL for hosting old versions of documentation

### ISSUE THREAD

**Issue by aetter** [opendistro-for-elasticsearch/opendistro-build#621]
**Is your feature request related to a problem? Please describe.**
We currently nest old versions of the documentation within the documentation itself, which creates a weird recursive situation where the 1.12 documentation contains a full copy of the 0.9 and 1.11 documentation, which contains another full copy of the 0.9 documentation. The problem will get worse as we start hosting more versions.

**Describe the solution you'd like**
We should add an S3 bucket and CloudFront URL and give write permissions to the documentation team. That way, we can upload a new version of the documentation every time we [tag a release](https://github.com/opendistro/for-elasticsearch-docs/releases) and have somewhere to permalink.

**Comment by peterzhuamazon** [comment]
Thanks @aetter we will add this to our roadmap.
Will work on it once we complete the current releases.

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @aetter we have a new setup for the website now, so will close this issue now.
