### ISSUE TITLE
How to install plugins on Helm deployment

### ISSUE THREAD

**Issue by cdpierse** [opendistro-for-elasticsearch/opendistro-build#630]
**Query**
Hi,

I’ve been searching the documentation for some information around installing custom plugins on my cluster that is deployed on k8s via Helm. I can’t seem to find anything concrete and am a bit confused. For context, I’m looking to install the Azure repository to enable snapshots.

I’ve been able to attach single pods in my Kubernetes setup and install the plugin manually via

    sudo bin/elasticsearch-plugin install repository-azure

But this approach doesn’t make much sense as I’d have to attach to every pod in the Kubernetes cluster and do the same, and I don’t think it would take effect without a restart which I don’t think would persist.

Even with Azure repository plugin installed I would then need to configure it with my Azure storage settings and I’m not sure where I would do this either, my best guess is via elasticsearch.yml.

Any suggestions or advice would be of great help.

Thanks!

**Expected Behavior**
I'd like to be able to install plugins on my cluster when using helm. Ideally, I would predefine which plugins so they could be installed on each node.

**Comment by sreekarjami** [comment]
Hi @cdpierse , 
Thanks for opening the issue. At present we don't have the feature to install the plugins without manual intervention. The other way to minimize the impact is to change the ODFE docker image and include the required plugins and perform a blue-green deployment. If you are able to find a fix which makes it easy for the installation, please feel free to open a PR. 

Thanks again !!

**Comment by cdpierse** [comment]
@sreekarjami Thanks for the response and thanks for clarifying the situation with plugins. It seems like installing a plugin to a already deployed instance on K8s would still trigger restarts for for node, the only clean solution would be to install all plugins for a fresh ES instance on initial startup but  I think changing the base image with required plugins is probably the simplest solution, thanks for the suggestion.
