### ISSUE TITLE
ODFE 1.13.1 based on ES 7.10.2

### ISSUE THREAD

**Issue by sreekarjami** [opendistro-for-elasticsearch/opendistro-build#653]
ODFE 1.13.1 based on ES 7.10.2

Release Engineering / Build Repo Key Changes:

- Bug fix for Performance Analyzer plugin in TAR and Docker (#649)

**Comment by webwurst** [comment]
Will this bug fix also be included? https://github.com/opendistro-for-elasticsearch/security/pull/1048
> Unexpected exception cluster:monitor/health when GET _cat/health

**Comment by bbarani** [comment]
@webwurst , Yes this release will also include this [fix](https://github.com/opendistro-for-elasticsearch/security/pull/1048).
