### ISSUE TITLE
Performance issue between version 1.11.0 and 1.13.0

### ISSUE THREAD

**Issue by vinaykumar4s** [opendistro-for-elasticsearch/opendistro-build#664]
I see considerable Performance degradation between the versions 1.11.0 and 1.13.0. I do not know which section this issue belongs to so i am opening issue in opendistro-build section.   I tried to sample data in both versions  on the same machine and view the the dashboard. version 1.11.0 is loading very fast when compared with 1.13.0. The difference is lot. its in seconds.
i have not tested with actual data.

Open distro version 1.11.0
![image](https://user-images.githubusercontent.com/25397819/109050093-04f96000-76a7-11eb-8742-fcc8900c7b7f.png)

Open distro version 1.13.0
![image](https://user-images.githubusercontent.com/25397819/109050080-01fe6f80-76a7-11eb-915c-47a2e5690940.png)

**Comment by bbarani** [comment]
@vinaykumar4s, Can you provide more details on your use case? It would be great if you can list the steps you followed to better understand the performance issue.

**Comment by vinaykumar4s** [comment]
Hi @bbarani ,
I have currently dev server running opendistro 1.11.0 version on a single node. It was installed from tar.gz distribution of opendistro.  I am running as  independent process using /bin/elasticsearch. As far as data, we don’t have so much data and it’s not very heavy user base. Performance is good in that node. I don’t see any lags in that server. Now. I am trying to setup in stage env. So I thought of using latest version opendistro in so I can get all the features including reports.  I have setup latest in stage env using yum package manager it is RHEL v8. 


OS version:
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"

Reproduce steps:
Opendistro version 1.11.0
1.	 Download tar.gz version - 1.11.0
2.	 Extract distribution
3.	Execute ./opendistro-tar-install.sh
4.	Download kibana tar.gz version - 1.11.0
5.	Extract kibana distribution
6.	Execute ./bin/kibana
7.	Go to local host localhost:5601
8.	Username and password: admin:admin
9.	Add sample data
10.	Select Sample eCommerce orders
11.	Open dashboard [eCommerce] Revenue Dashboard in dashboard section
12.	In browser dev/inspect tools check the request loading timings.

Follow the same steps for version 1.13.0 or you can install using yum (https://opendistro.github.io/for-elasticsearch-docs/docs/install/rpm/). You can see the difference in loading pages. Not only dashboard, I see the differences in Discover mode also.  Please note that I have not customized any of the internal configurations in both situations. I kept default confutations as it is.

On the side can you tell me how can i download previous versions of tar.gz distributions? In the webisite i only see the link download latest versions.

Thank you.

**Comment by mxmorin** [comment]
I've same issue in all the masters (3 nodes). These nodes are ingest nodes too and receive bulks.
No effect on data nodes only.

![image](https://user-images.githubusercontent.com/58942529/109125360-455ee980-774c-11eb-9fa3-394ee7271878.png)

First peak in after the ugrade. Bulk operations failed with timeout and masters became instable. 
Bulks have been redirected to data node and cpu usage decreased but still be more than previous version.

With hot_threads, we have this result.
Is it due to BouncyCastle upgrade ?

![image](https://user-images.githubusercontent.com/58942529/109125107-f749e600-774b-11eb-8732-dfc88a0733a0.png)

**Comment by bbarani** [comment]
> Hi @bbarani ,
> I have currently dev server running opendistro 1.11.0 version on a single node. It was installed from tar.gz distribution of opendistro. I am running as independent process using /bin/elasticsearch. As far as data, we don’t have so much data and it’s not very heavy user base. Performance is good in that node. I don’t see any lags in that server. Now. I am trying to setup in stage env. So I thought of using latest version opendistro in so I can get all the features including reports. I have setup latest in stage env using yum package manager it is RHEL v8.
> 
> OS version:
> NAME="Red Hat Enterprise Linux"
> VERSION="8.2 (Ootpa)"
> ID="rhel"
> ID_LIKE="fedora"
> VERSION_ID="8.2"
> PLATFORM_ID="platform:el8"
> PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
> HOME_URL="https://www.redhat.com/"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
> REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
> REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
> REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
> 
> Reproduce steps:
> Opendistro version 1.11.0
> 
> 1. Download tar.gz version - 1.11.0
> 2. Extract distribution
> 3. Execute ./opendistro-tar-install.sh
> 4. Download kibana tar.gz version - 1.11.0
> 5. Extract kibana distribution
> 6. Execute ./bin/kibana
> 7. Go to local host localhost:5601
> 8. Username and password: admin:admin
> 9. Add sample data
> 10. Select Sample eCommerce orders
> 11. Open dashboard [eCommerce] Revenue Dashboard in dashboard section
> 12. In browser dev/inspect tools check the request loading timings.
> 
> Follow the same steps for version 1.13.0 or you can install using yum (https://opendistro.github.io/for-elasticsearch-docs/docs/install/rpm/). You can see the difference in loading pages. Not only dashboard, I see the differences in Discover mode also. Please note that I have not customized any of the internal configurations in both situations. I kept default confutations as it is.
> 
> On the side note, Can you tell me how can i download previous versions of tar.gz distributions? In the webisite i only see the link to download latest versions.
> 
> Thank you.

Thanks for the steps. We will look in to this issue and update our findings in this thread.

You can download the previous versions using the below cloudfront link (Just replace the version number with the one you want to download).

https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistro-elasticsearch/opendistroforelasticsearch-1.11.0.tar.gz

**Comment by mxmorin** [comment]
I confirm performance issue since upgrade to 1.13 from 1.12 version.
Queries and bulks are very slow

Is there a way to downgrade to 1.12 ?

**Comment by mxmorin** [comment]
In my staging env, i've restarted all nodes with security plugin disabled.
Cpu on master and response time decreased immediatly  (0.500ms to 0.100ms for the same query via curl)

![image](https://user-images.githubusercontent.com/58942529/109309049-111a2480-7843-11eb-81fe-f25d972a7389.png)

**Comment by bbarani** [comment]
@vinaykumar4s @mxmorin we have zeroed in on the root cause of this performance issue and currently testing our fix. We are working on pushing the fix in a patch release (by this week or next). I will keep this thread updated with the progress.

**Comment by bbarani** [comment]
@vinaykumar4s  We have added a new page to download [previous versions](https://opendistro.github.io/for-elasticsearch-docs/docs/previousversions/). Let me know if you have any questions.

**Comment by vinaykumar4s** [comment]
@bbarani thank you. I will wait for the patch and I will update my results after applying patch. Right now I have downgraded to 1.11.0 and everything great on 1.11.0.

**Comment by bbarani** [comment]
@vinaykumar4s @mxmorin The patch version is out and you can download it now from [downloads page](https://opendistro.github.io/for-elasticsearch/downloads.html#prod)

**Comment by vinaykumar4s** [comment]
@bbarani  i confirm the issues is resolved in 1.13.1. Thank you for quick turnaround.


![image](https://user-images.githubusercontent.com/25397819/110153394-fef33580-7db0-11eb-8364-258790d42f49.png)

**Comment by vinaykumar4s** [comment]
I confirm the issues is resolved in 1.13.1. Thank you for quick turnaround.
