### ISSUE TITLE
Unable to download the previous releases elasticsearch and kibana

### ISSUE THREAD

**Issue by logztechstuff** [opendistro-for-elasticsearch/opendistro-build#665]
**Query**
Unable to download the previous releases elasticsearch and kibana

**Expected Behavior**
From the version history page, if a specific version is chosen, it should take to download of the installer of the respective version.

**Current Behavior**
Irrespective of any release/version, the download page always takes to the latest version.

**Comment by bbarani** [comment]
@logztechstuff , Currently we do not have a page to download previous versions but as a workaround please use the below download URL's (after replacing the version placeholder) to download previous versions

https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistro-elasticsearch/opendistroforelasticsearch-[version].tar.gz
https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistroforelasticsearch-kibana/opendistroforelasticsearch-kibana-[version].tar.gz

**Comment by logztechstuff** [comment]
thanks, @bbarani. Whether this build is compatible with macOS?

**Comment by logztechstuff** [comment]
Kibana doesn't run on the macOS as the node binary bundled with Kibana is for Linux, not compatible with macOS. To run the Kibana in macOS, I followed the below steps.

- Remove node and node_modules from OpenDistro Kibana
- Download the macOS compatible Kibana from Elasticsearch where the Kibana version must be the same as the version used in OpenDistro. For each version of OpenDistro corresponding Elastic version can be referred [https://opendistro.github.io/for-elasticsearch-docs/version-history/](url)
- Extract the installer, copy the node and node_modules directories from Elastic's Kibana to OpenDistro Kibana.
- Remove the installer and extracted directory
