### ISSUE TITLE
yum repository unavailable

### ISSUE THREAD

**Issue by hubekpeter** [opendistro-for-elasticsearch/opendistro-build#674]
**Describe the bug**
Problem retrieving files from 'Release RPM artifacts of OpenDistroForElasticsearch'.
Permission to access 'https://d3g5vo6xdbdb9a.cloudfront.net/yum/noarch/media.1/media' denied.

**To Reproduce**
1. Install 'curl https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo -o /etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo'
2. Run 'zypper cc; zypper ref or yum clean all; yum makecache'
3. See error

**Expected behavior**
zypper, yum etc. will cache the repository metadata properly

**Configuration (please complete the following information):**
 - ODFE/Kibana version [latest]
 - Distribution [RPM]
 - Host Machine [OepnSuse 15.2, Centos 7]

**Relevant information**
It's happening since Saturday 12:30 (24H) CET timezone.

**Comment by sreekarjami** [comment]
Hi @hubekpeter,
Thanks for reaching out. I have tried to replicate and below are my results. 

[e ~]$ yum clean all
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Cleaning repos: amzn2-core amzn2extra-docker elasticsearch-6.x elasticsearch-7.x opendistroforelasticsearch-artifacts-repo
Cleaning up everything

[e ~]$ yum makecache
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                                                        | 3.7 kB  00:00:00     
amzn2extra-docker                                                                                                                 | 3.0 kB  00:00:00     
elasticsearch-6.x                                                                                                                 | 1.3 kB  00:00:00     
elasticsearch-7.x                                                                                                                 | 1.3 kB  00:00:00     
opendistroforelasticsearch-artifacts-repo/signature                                                                               |  836 B  00:00:00     
opendistroforelasticsearch-artifacts-repo/signature                                                                               | 3.4 kB  00:00:00 !!! 
(1/19): amzn2-core/2/x86_64/group_gz                                                                                              | 2.5 kB  00:00:00     
(2/19): amzn2-core/2/x86_64/updateinfo                                                                                            | 350 kB  00:00:00     
(3/19): amzn2-core/2/x86_64/filelists_db                                                                                          |  38 MB  00:00:00     
(4/19): amzn2-core/2/x86_64/other_db                                                                                              |  507 B  00:00:00     
(5/19): amzn2extra-docker/2/x86_64/updateinfo                                                                                     |   76 B  00:00:00     
(6/19): amzn2extra-docker/2/x86_64/filelists_db                                                                                   |  15 kB  00:00:00     
(7/19): amzn2extra-docker/2/x86_64/other_db                                                                                       |  507 B  00:00:00     
(8/19): amzn2extra-docker/2/x86_64/primary_db                                                                                     |  75 kB  00:00:00     
(9/19): amzn2-core/2/x86_64/primary_db                                                                                            |  50 MB  00:00:00     
(10/19): elasticsearch-6.x/primary                                                                                                | 171 kB  00:00:00     
(11/19): elasticsearch-6.x/filelists                                                                                              |  11 MB  00:00:00     
(12/19): elasticsearch-6.x/other                                                                                                  |  24 kB  00:00:00     
(13/19): elasticsearch-7.x/primary                                                                                                | 181 kB  00:00:00     
(14/19): elasticsearch-7.x/other                                                                                                  |  27 kB  00:00:00     
(15/19): opendistroforelasticsearch-artifacts-repo/prestodelta                                                                    |   78 B  00:00:00     
(16/19): elasticsearch-7.x/filelists                                                                                              |  12 MB  00:00:00     
(17/19): opendistroforelasticsearch-artifacts-repo/primary_db                                                                     |  92 kB  00:00:00     
(18/19): opendistroforelasticsearch-artifacts-repo/filelists_db                                                                   | 6.8 MB  00:00:00     
(19/19): opendistroforelasticsearch-artifacts-repo/other_db                                                                       |  13 kB  00:00:00     
elasticsearch-6.x                                                                                                                                546/546
elasticsearch-6.x                                                                                                                                546/546
elasticsearch-6.x                                                                                                                                546/546
elasticsearch-7.x                                                                                                                                616/616
elasticsearch-7.x                                                                                                                                616/616
elasticsearch-7.x                                                                                                                                616/616
Metadata Cache Created


I have not encountered any errors while trying to replicate. 

Can you please run and share your results.

**Comment by hubekpeter** [comment]
Hi Sreekarjami, 
yes I can confirm it's up and running again.
Thanks
P.

elkstack:/etc/zypp/repos.d # zypper ref
Repository 'Elasticsearch repository for 7.x packages' is up to date.                                                                                                                                                                         
Retrieving repository 'Elasticsearch repository for 6.x packages' metadata .............................................................................................................................................................[done]
Building repository 'Elasticsearch repository for 6.x packages' cache ..................................................................................................................................................................[done]
Retrieving repository 'Elasticsearch repository for 7.x packages' metadata .............................................................................................................................................................[done]
Building repository 'Elasticsearch repository for 7.x packages' cache ..................................................................................................................................................................[done]
Retrieving repository 'Release RPM artifacts of OpenDistroForElasticsearch' metadata ...................................................................................................................................................[done]
Building repository 'Release RPM artifacts of OpenDistroForElasticsearch' cache ........................................................................................................................................................[done]
Repository 'Non-OSS Repository' is up to date.                                                                                                                                                                                                
Repository 'Main Repository' is up to date.                                                                                                                                                                                                   
Repository 'Main Update Repository' is up to date.                                                                                                                                                                                            
Repository 'Update Repository (Non-Oss)' is up to date.                                                                                                                                                                                       
All repositories have been refreshed.
