### ISSUE TITLE
How are the variables in the values.yaml file defined?

### ISSUE THREAD

**Issue by MitHub7** [opendistro-for-elasticsearch/opendistro-build#675]
https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/b42c52309f05dd9d28accaaf0abbf7c795d0763f/helm/opendistro-es/values.yaml#L454

Hello,

In the `elasticsearch.config` part of the **values.yaml** file, there is these variables like ${CLUSTER_NAME}, ${NODE_MASTER}, ${HTTP_ENABLE} that are referenced but its unclear to me where these should be defined.

Can you please tell me how and where these variables are supposed to be defined first? Or are we just supposed to replace them by hard-coded values?

**Comment by sreekarjami** [comment]
Hi @MitHub7,
Thanks for opening the issue. There are different ways to assign values during the helm install. Please follow this [link](https://helm.sh/docs/chart_template_guide/values_files/), which should provide all the different options and how you can use them.  

Please inform if you still have any concerns.

**Comment by MitHub7** [comment]
Hello @sreekarjami, thanks for answering.
I already know about helm values. Here I am specifically asking about variables that exists within the values.yaml file itself. 
Take for example the variable I gave as an example : **name: ${CLUSTER_NAME}** 

Where is this variable ${CLUSTER_NAME} supposed to be defined?

**Comment by sreekarjami** [comment]
Hi @MitHub7 ,
The value of the variable ${CLUSTER_NAME} can be hardcoded in the values.yml or you can pass it using -set flag during the install dynamically.
