### ISSUE TITLE
Data Prepper 0.8.0

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/opendistro-build#683]
Release:

Data Prepper will have a patch release on the earlier released 0.8.0. This release is planned for March 18th. The required artifacts and repo tags will be provided to the opendistro release team before March 15th.

**Comment by peterzhuamazon** [comment]
Thanks @kowshikn will work with @wrijeff on this.

**Comment by peterzhuamazon** [comment]
Update 20210319:

@wrijeff has provided the artifacts and tag, I have synced the artifacts to staging, and build the docker image for staging.
Please verify.

Thanks.

**Comment by wrijeff** [comment]
Confirmed staged docker image works with: `docker run --name data-prepper --expose 21890 -v /home/ec2-user/example-pipelines.yaml:/usr/share/data-prepper/pipelines.yaml -v /home/ec2-user/example-data-prepper-config.yaml:/usr/share/data-prepper/data-prepper-config.yaml <image_name>`

Will verify artifacts next.

**Comment by wrijeff** [comment]
Downloaded artifacts from S3, confirmed checksums match what was provided.

**Comment by peterzhuamazon** [comment]
Update 20210325:

@wrijeff the prod artifacts and docker have been pushed and synced. Please check the results and sign-off the artifacts.

Thanks.

**Comment by wrijeff** [comment]
Confirmed docker images work as expected.

Spot-checked 3 prod artifacts, confirmed all checksums matched what was expected.

**Comment by peterzhuamazon** [comment]
Thanks, will close this issue for now.
