### ISSUE TITLE
Indentation bug in values file : SecurityConfig configuration of elasticsearch  

### ISSUE THREAD

**Issue by mdiver** [opendistro-for-elasticsearch/opendistro-build#687]
**Describe the bug**
opendistro-build/helm/opendistro-es/values.yaml
Lines 175 to 181 have 3 spaces instead of 2

![스크린샷 2021-03-15 23 09 02](https://user-images.githubusercontent.com/37290743/111166542-89bf0600-85e3-11eb-97f7-fa897ce2eff2.png)

**Comment by peterzhuamazon** [comment]
Thanks @mdiver we have approved and merged this PR.
