### ISSUE TITLE
Module is outdated

### ISSUE THREAD

**Issue by TobiasK22** [opendistro-for-elasticsearch/opendistro-build#7]
I try to run opendistro-for-elasticsearch on a openshift-container but I get this error:
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

**Comment by alolita** [comment]
@TobiasK22 are you still having this problem? Did you upgrade to Open Distro 1.2.0. Let us know and we can take a look if you're still running into setup issues.

**Comment by rauizab** [comment]
Hi, we are having the same problem with 1.2.1
```
{"type":"log","@timestamp":"2019-12-17T13:39:25Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for opendistro-alerting, security-login, security-customerror, security-multitenancy, security-accountinfo, security-configuration, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
```

We are running the docker image "amazon/opendistro-for-elasticsearch-kibana:1.2.1"
Could you help us fixing it?

Best regards

**Comment by weicongs-amazon** [comment]
This is very old issue. I don't see the same error in the latest version. close this one. If you do see the issue, feel free to reopen it.
