### ISSUE TITLE
GPG Key import failing while installing OpenDistros ES via RPM

### ISSUE THREAD

**Issue by reshrama** [opendistro-for-elasticsearch/opendistro-build#72]
Hi Guys,

I am trying to install OpenDistros ES into an EC2 instance via RPM package. 
While creating the repository file via the command: `sudo curl https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo -o /etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo`  I am getting the below error:

`Retrieving key from https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch
Importing GPG key 0xE370325E:
 Userid     : "OpenDistroForElasticsearch (Key For signing OpenDistroForElasticsearch artifacts.) <opendistroforelasticsearch-infra@amazon.com>"
 Fingerprint: 5120 9ccb 28fb c2dc 8ccd 9a6c 472c fdfc e370 325e
 From       : https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch
https://d3g5vo6xdbdb9a.cloudfront.net/yum/noarch/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo opendistroforelasticsearch-artifacts-
repo
Trying other mirror.
failure: repodata/repomd.xml from opendistroforelasticsearch-artifacts-repo: [Errno 256] No more mirrors to try.
https://d3g5vo6xdbdb9a.cloudfront.net/yum/noarch/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo opendistroforelasticsearch-artifacts-
repo`

I tried executing `https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch` which is the GPG Key url for OpenDistros ES in my local and it is getting installed fine.

I am not sure why the import is failing in EC2. Any leads would be appreciated.

Attaching the artefact file.
[opendistroses.docx](https://github.com/opendistro-for-elasticsearch/opendistro-build/files/4151757/opendistroses.docx)

**Comment by rishabh6788** [comment]
I just tried installing RPM distribution on an EC2 instance running Amazon Linux and it went through without an issue.

Can you once try deleting '/etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo' file and reinstalling the ES again?

If it still fails can you please provide the content of "/etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo" file ?

**Comment by weicongs-amazon** [comment]
close it. feel free to reopen it if you still have issue
