### ISSUE TITLE
403 when downloading plugin

### ISSUE THREAD

**Issue by ajbeach2** [opendistro-for-elasticsearch/opendistro-build#730]
I am trying to run the following and the plugin URL is 403 

```
sudo bin/elasticsearch-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-security/opendistro-security-1.8.0.0.zip
```

Where can I download older plugin versions?

**Comment by gaiksaya** [comment]
Hi @ajbeach2 ,
For all previous versions (before `1.13.0.0`) of security plugin, the security plugin zip is named as `opendistro_security-<version>.zip`
https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-security/opendistro_security-1.8.0.0.zip
Sorry for the confusion.

**Comment by cliu123** [comment]
@gaiksaya Thanks for providing the correct link!
@ajbeach2 The link provided above works for me. Please re-open the issue in case that it doesn't work for you.
