### ISSUE TITLE
1.13.3 is not patched for Log4J vulnerability

### ISSUE THREAD

**Issue by FirstWhack** [opendistro-for-elasticsearch/opendistro-build#798]
**Describe the bug**
Patch source was not released and the patched version is using  log4j:log4j-core:2.13.0

**Comment by FirstWhack** [comment]
Ah whatever, I'll just go to Open Search.

**Comment by bbarani** [comment]
@FirstWhack FYI.. We didn't replace the log4J library rather we removed the JNDI classes from the path. You can view more details on the fix [here](https://discuss.opendistrocommunity.dev/t/log4j2-vulnerability-in-opensearch/7935/41)
