### ISSUE TITLE
Migrate from 9.0 to 1.0

### ISSUE THREAD

**Issue by r00t9** [opendistro-for-elasticsearch/opendistro-build#8]
I install opendistro 1.0 and elasticsearch-oss 7.0.1 and when i tried to run securityadmin i get this error.

Command: 

`./securityadmin.sh -migrate ~/elastic_backup -nhnv -cacert /etc/elasticsearch/root-ca.pem -cert /etc/elasticsearch/kirk.pem -key /etc/elasticsearch/kirk-key.pem`

>  opendistro_security index already exists, so we do not need to create one.
> Legacy index '.opendistro_security' (ES 6) detected (or forced). You should migrate the configuration!

>Will retrieve 'security/internalusers' into ~/elastic_backup/internal_users.yml (legacy mode)
>ERR: Seems internalusers from cluster is not in legacy format: >com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field >"password" (class >com.amazon.opendistroforelasticsearch.security.securityconf.impl.v6.InternalUserV6), not marked >as ignorable (6 known properties: "readonly", "username", "attributes", "hidden", "roles", "hash"])
> at [Source: {"logstash":{"roles":["logstash"],"test":{"password":"","roles":[],"snapshotrestore": {"roles":["snapshotrestore"],"admin":{"readonly":"true","roles":["admin"],"attributes":{"attribute1":"value1","attribute3":"value3","attribute2":"value2"},"kibanaserver":{"readonly":"true","kibanaro":{"roles":["kibanauser","readall"]},"readall":{"roles":["readall"]; line: 1, column: 126] (through reference chain: >com.amazon.opendistroforelasticsearch.security.securityconf.impl.SecurityDynamicConfiguration["test"]->com.amazon.opendistroforelasticsearch.security.securityconf.impl.v6.InternalUserV6["password"])
>Will retrieve 'security/actiongroups' into ~/elastic_backup/action_groups.yml (legacy mode)
   SUCC: Configuration for 'actiongroups' stored in ~/elastic_backup/action_groups.yml

**Comment by q2dg** [comment]
Now there's ElasticSearch 7.3 already ....

**Comment by alolita** [comment]
@r00t9 are you still having this issue? Or have you upgraded to the latest version 1.2.0?

**Comment by r00t9** [comment]
Now i couldn't fix it, so i just a make a clean installation. I don't know if the latest version 1.2.0 is fix it with this issue.
