### ISSUE TITLE
Shasum for the tarball assumes it resides in a subdirectory

### ISSUE THREAD

**Issue by aetter** [opendistro-for-elasticsearch/opendistro-build#81]
Following the installation steps from the tarball guide (at https://opendistro.github.io/for-elasticsearch-docs/docs/install/tar/) fails at step 3 "verify the tarball against the checksum".

The checksum file seems to assume that the downloaded tarball sits in a `tarfiles/` subdirectory.

```bash
$ shasum -a 512 -c opendistroforelasticsearch-1.4.0.tar.gz.sha512
shasum: ./tarfiles/opendistroforelasticsearch-1.4.0.tar.gz: 
./tarfiles/opendistroforelasticsearch-1.4.0.tar.gz: FAILED open or read
shasum: WARNING: 1 listed file could not be read
```

1.2.0 works. 1.3.0 doesn't, so the issue cropped up between those two releases.

**Comment by peterzhuamazon** [comment]
Thanks @aetter for reporting this issue in our workflow.
We have fixed the issue in PR #249, and will use it in our next releases.
We will close this issue as it is resolved for now.
