### ISSUE TITLE
Can you clarify your position about Windows support?

### ISSUE THREAD

**Issue by treilhes** [opendistro-for-elasticsearch/opendistro-build#99]
Hello,
For now, everything i've read about running opendistro for elasticsearch on windows imply running it using a docker image.

So can you answer the following questions:
- Do/will you support running your distribution directly on Windows platforms?
- Do/will you support running all your custom plugins directly on Windows platforms?
- Can i expect the same level of support/testing/tooling on Windows platforms?

PS: I know java is meant to run the same on Windows than on Linux but the real life is more crual than the start of this sentence.

**Comment by j0hnth0m** [comment]
I also noticed that the <es_home>\bin folder no longer contains the elasticsearch-service-*.exe's.

**Comment by weicongs-amazon** [comment]
The duplicated issue with https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/112. close this one
